# -*- coding: utf-8 -*-
"""Single source for the GRS data model figures and tables.

The detail figure (F-011) and the column table are generated from ENTITIES so
they cannot disagree. Column names follow table T-006a: W-2 camelCase, W-8 keeps
the exchange partner's stem, W-9 keeps the partner's spelling inside carry only,
W-10 prefixes GRS-own booleans with is/has/can.

Fields per column: (name, type, nullable, key, fk, origin, mspdi, meaning)
  key    '' | 'PK' | 'FK' | 'PK/FK'
  origin Own | Consume | GRS | Carry
"""

ROOT = [
    ('schemaVersion', '文字列', '否', '', '', 'GRS', '',
     '文書の形式の版。判別は `FR-073`'),
    ('schedule', 'オブジェクト', '否', '', '', 'GRS', '',
     '日程データの群（表 T-052 の `DR-2`）'),
    ('documentSettings', 'オブジェクト', '否', '', '', 'GRS', '',
     '見せ方の群（同 `DR-3`）。鍵と値は `tbl-settings.md`'),
    ('revisionStamp', 'オブジェクト', '否', '', '', 'GRS', '',
     '版数・最後に書いた者・時刻（同 `DR-4`）'),
    ('changeLog', '配列', '否（空可）', '', '', 'GRS', '',
     '変更の理由（同 `DR-4`）'),
]

SCHEDULE = [
    ('project', 'オブジェクト', '否', '', '', 'GRS', '', '文書が表す 1 つのプロジェクト'),
    ('calendars', '`Calendar[]`', '否（空可）', '', '', 'GRS', '', '暦'),
    ('tasks', '`Task[]`', '否（空可）', '', '', 'GRS', '', 'タスク。依存はこの下に入れ子'),
    ('resources', '`Resource[]`', '否（空可）', '', '', 'GRS', '', '担当者'),
    ('assignments', '`Assignment[]`', '否（空可）', '', '', 'GRS', '', '割当'),
    ('taskGroups', '`TaskGroup[]`', '否（空可）', '', '', 'GRS', '', '行の器'),
    ('taskGroupMembers', '`TaskGroupMember[]`', '否（空可）', '', '', 'GRS', '', 'どのタスクがどの行に載るか'),
    ('taskVisuals', '`TaskVisual[]`', '否（空可）', '', '', 'GRS', '', 'タスクの見せ方'),
    ('commentBoxes', '`CommentBox[]`', '否（空可）', '', '', 'GRS', '', 'コメントボックス'),
    ('highlightBoxes', '`HighlightBox[]`', '否（空可）', '', '', 'GRS', '', 'ハイライトボックス'),
    ('taskOrigins', '`TaskOrigin[]`', '否（空可）', '', '', 'GRS', '', '取り込み元の記録'),
]

ENTITIES = [
 ('Project', 'プロジェクトの基本情報と、文書ぜんたいに掛かる暦の既定', [
    ('id', '文字列（16 字以下）', '可', '', '', 'Own', 'Project/UID',
     '⚠️ **主キーにしない**（理由は Chapter 5.4）。'
     '省略されたときは `TaskOrigin.importSessionId` が代わりを務める'),
    ('name', '文字列', '可', '', '', 'Own', 'Project/Name', 'プロジェクト名'),
    ('title', '文字列', '可', '', '', 'Own', 'Project/Title', '表題'),
    ('subject', '文字列', '可', '', '', 'Own', 'Project/Subject', '件名'),
    ('category', '文字列', '可', '', '', 'Own', 'Project/Category', '分類'),
    ('company', '文字列', '可', '', '', 'Own', 'Project/Company', '会社名'),
    ('manager', '文字列', '可', '', '', 'Own', 'Project/Manager', '管理者名'),
    ('author', '文字列', '可', '', '', 'Own', 'Project/Author', '**作成者。最後に書いた者ではない**'),
    ('created', '日時', '可', '', '', 'Own', 'Project/CreationDate', '作成日時'),
    ('revision', '整数', '可', '', '', 'Own', 'Project/Revision', '⚠️ **交換相手の保存回数。`revisionStamp.revision` とは別物**'),
    ('lastSaved', '日時', '可', '', '', 'Own', 'Project/LastSaved', '最後に保存した日時'),
    ('startDate', '日付', '可', '', '', 'Own', 'Project/StartDate', 'プロジェクトの開始日'),
    ('statusDate', '日付', '可', '', '', 'Own', 'Project/StatusDate', '基準日線が立つ日'),
    ('minutesPerDay', '整数', '可', '', '', 'Own', 'Project/MinutesPerDay', '1 日あたりの分数。期間の換算に使う'),
    ('minutesPerWeek', '整数', '可', '', '', 'Own', 'Project/MinutesPerWeek', '1 週あたりの分数'),
    ('daysPerMonth', '整数', '可', '', '', 'Own', 'Project/DaysPerMonth', '1 か月あたりの日数'),
    ('weekStartDay', '整数（0〜6）', '可', '', '', 'Own', 'Project/WeekStartDay', '週の始まりの曜日'),
    ('calendarUid', '整数', '可', 'FK', '`Calendar.uid`', 'Consume', 'Project/CalendarUID', '既定の暦'),
    ('themeHue', '整数（0〜359）', '否', '', '', 'GRS', '',
     'テーマの色相。置き場は表 T-052 の `DR-5`、値は `tbl-settings.md` の `S-73`'),
    ('uidHighWaterMark', '整数', '否', '', '', 'GRS', '',
     '発番済みの `uid` の最大値。**複製（`FR-033`）の採番はここに従う**'),
    ('carry', '連想（文字列→文字列）', '否（空可）', '', '', 'Carry', '', '解釈しない `Project` 直下のスカラー'),
    ('carryElements', '`CarryElement[]`', '否（空可）', '', '', 'Carry', '', '行にならなかった子要素（表 T-053 の `DF-3`）'),
 ]),
 ('Task', 'タスク 1 つ。予定と実績を同じ行が持つ', [
    ('uid', '整数', '否', 'PK', '', 'Own', 'Task/UID', '文書内で一意・不変。**値から意味を読まない**'),
    ('wbsParentUid', '整数', '可（`null` = 根）', 'FK', '`Task.uid`', 'Consume', '',
     'WBS の親。交換相手には対応要素が無く、深さと出現順から起こす'),
    ('wbsOrder', '整数', '可', '', '', 'Consume', '', '同じ親の下での並び'),
    ('name', '文字列', '可', '', '', 'Own', 'Task/Name', 'タスク名'),
    ('start', '日時', '可', '', '', 'Own', 'Task/Start', '予定の開始'),
    ('finish', '日時', '可', '', '', 'Own', 'Task/Finish', '予定の終了'),
    ('milestone', '真偽', '可', '', '', 'Own', 'Task/Milestone',
     '**マイルストーンかどうかの正。** 描画の形（`TaskVisual.shapeKind`）とは別（表 T-016 の `PR-18`）'),
    ('deadline', '日時', '可', '', '', 'Own', 'Task/Deadline', '期限'),
    ('notes', '文字列', '可', '', '', 'Own', 'Task/Notes', '備考'),
    ('calendarUid', '整数', '可', 'FK', '`Calendar.uid`', 'Consume', 'Task/CalendarUID', 'このタスクが使う暦'),
    ('actualStart', '日時', '可', '', '', 'Own', 'Task/ActualStart', '実績の開始。空 = 未着手'),
    ('actualDuration', '整数（稼働日）', '可', '', '', 'Own', 'Task/ActualDuration', '実績バーの長さ'),
    ('actualFinish', '日時', '可', '', '', 'Own', 'Task/ActualFinish', '**完了したときだけ入る**'),
    ('resume', '日時', '可', '', '', 'Own', 'Task/Resume', '中断中に、残りが始まる予定の日'),
    ('resumeValid', '真偽', '可', '', '', 'Own', 'Task/ResumeValid', '偽 = 再開日が未定の中断'),
    ('percentComplete', '整数（0 以上）', '可', '', '', 'Own', 'Task/PercentComplete',
     '完了率。**上限を型に持たせない**（`FR-012`）'),
    ('fadeInDays', '整数（日数）', '可', '', '', 'Consume', 'Task/ExtendedAttribute',
     '左のぼかしの日数。`null` と `0` を区別する'),
    ('fadeOutDays', '整数（日数）', '可', '', '', 'Consume', 'Task/ExtendedAttribute', '右のぼかしの日数。同上'),
    ('dependencies', '`Dependency[]`', '否（空可）', '', '', 'Consume', 'Task/PredecessorLink',
     '**このタスクを後続とする依存**（表 T-053 の `DF-4`）'),
    ('carry', '連想（文字列→文字列）', '否（空可）', '', '', 'Carry', '', '解釈しない `Task` 直下のスカラー'),
    ('carryElements', '`CarryElement[]`', '否（空可）', '', '', 'Carry', '', '行にならなかった子要素'),
 ]),
 ('Dependency', '依存 1 本。**後続タスクの下に入れ子で持つ**', [
    ('predecessorUid', '整数', '否', 'FK', '`Task.uid`', 'Consume', 'PredecessorLink/PredecessorUID',
     '先行タスク。**後続は入れ子の位置が表す**'),
    ('linkType', '整数（0〜3）', '否', '', '', 'Consume', 'PredecessorLink/Type',
     '依存の種別。`0` = FF / `1` = FS / `2` = SF / `3` = SS'),
    ('lag', '整数', '可', '', '', 'Consume', 'PredecessorLink/LinkLag', 'ラグ。単位は `lagFormat`'),
    ('lagFormat', '整数', '可', '', '', 'Consume', 'PredecessorLink/LagFormat', 'ラグの単位'),
    ('carry', '連想（文字列→文字列）', '否（空可）', '', '', 'Carry', '', '`CrossProject` ほか、解釈しないスカラー'),
    ('carryElements', '`CarryElement[]`', '否（空可）', '', '', 'Carry', '', '行にならなかった子要素'),
 ]),
 ('TaskGroup', '行の器。縦積みの軸を作る（`FR-004`）', [
    ('id', '文字列（UUID）', '否', 'PK', '', 'GRS', '', '行の識別子'),
    ('parentId', '文字列（UUID）', '可（`null` = 根）', 'FK', '`TaskGroup.id`', 'GRS', '', '親の行。深さの上限は `FR-004`'),
    ('label', '文字列', '可（`null` = 導出）', '', '', 'GRS', '', '行の名前'),
    ('derivedFromTaskUid', '整数', '可', 'FK', '`Task.uid`', 'GRS', '', '名前の導出元。`label` と同時に `null` にできない'),
    ('order', '整数', '可', '', '', 'GRS', '', '同じ親の下での並び'),
    ('isCollapsed', '真偽', '可', '', '', 'GRS', '', '畳んでいるか'),
    ('color', '文字列', '可（`null` = テーマから解く）', '', '', 'GRS', '', '行の帯の色'),
    ('height', '整数', '可（`null` = 自動）', '', '', 'GRS', '', '倍率 1 のときの論理の高さ'),
 ]),
 ('TaskGroupMember', 'どのタスクがどの行の何段目に載るか', [
    ('taskUid', '整数', '否', 'PK/FK', '`Task.uid`', 'GRS', '',
     '載るタスク。**1 つのタスクは 1 行にしか載らない**ので、これだけで一意である'),
    ('groupId', '文字列（UUID）', '否', 'FK', '`TaskGroup.id`', 'GRS', '', '載せる行'),
    ('stackOrder', '整数', '可（`null` = 自動）', '', '', 'GRS', '', '段。人が指定できるかは表 T-014 の `ST-6`'),
 ]),
 ('Calendar', '暦 1 つ。稼働日と非稼働日を決める', [
    ('uid', '整数', '否', 'PK', '', 'Own', 'Calendars/Calendar/UID', '暦の識別子'),
    ('name', '文字列', '可', '', '', 'Own', 'Calendars/Calendar/Name', '暦の名前'),
    ('isBaseCalendar', '真偽', '可', '', '', 'Own', 'Calendars/Calendar/IsBaseCalendar', '基準の暦か'),
    ('baseCalendarUid', '整数', '可', 'FK', '`Calendar.uid`', 'Consume', 'Calendars/Calendar/BaseCalendarUID', '継承元の暦'),
    ('ordinal', '整数', '否', '', '', 'GRS', '', '出現順。書き出しで元の並びに戻す'),
    ('carry', '連想（文字列→文字列）', '否（空可）', '', '', 'Carry', '', '解釈しないスカラー'),
    ('carryElements', '`CarryElement[]`', '否（空可）', '', '', 'Carry', '', '`WorkWeeks` ほか、行にならなかった子要素'),
 ]),
 ('WeekDay', '曜日ごとの稼働の定め（弱エンティティ）', [
    ('calendarUid', '整数', '否', 'PK/FK', '`Calendar.uid`', 'GRS', '', '親の暦'),
    ('ordinal', '整数', '否', 'PK', '', 'GRS', '', '親の中での出現順'),
    ('dayType', '整数（1〜7）', '可', '', '', 'Own', 'Calendars/Calendar/WeekDays/WeekDay/DayType', '曜日'),
    ('dayWorking', '真偽', '可', '', '', 'Own', 'Calendars/Calendar/WeekDays/WeekDay/DayWorking', '稼働日か'),
    ('carry', '連想（文字列→文字列）', '否（空可）', '', '', 'Carry', '', '解釈しないスカラー'),
    ('carryElements', '`CarryElement[]`', '否（空可）', '', '', 'Carry', '', '`WorkingTimes` ほか'),
 ]),
 ('Exception', '暦の例外日（弱エンティティ）', [
    ('calendarUid', '整数', '否', 'PK/FK', '`Calendar.uid`', 'GRS', '', '親の暦'),
    ('ordinal', '整数', '否', 'PK', '', 'GRS', '', '親の中での出現順'),
    ('name', '文字列', '可', '', '', 'Own', 'Calendars/Calendar/Exceptions/Exception/Name', '例外の名前'),
    ('fromDate', '日時', '可', '', '', 'Own', '…/Exception/TimePeriod/FromDate', '⚠️ **繰り返しの起点であって実日付の範囲ではない**'),
    ('toDate', '日時', '可', '', '', 'Own', '…/Exception/TimePeriod/ToDate', '同上'),
    ('dayWorking', '真偽', '可', '', '', 'Own', '…/Exception/DayWorking', '稼働日か'),
    ('recurrenceKind', '整数（1〜9）', '可', '', '', 'Consume', '…/Exception/Type',
     '**繰り返しの種別。これを読まないと毎年 1 日の祝日が何年ぶんも非稼働になる**'),
    ('carry', '連想（文字列→文字列）', '否（空可）', '', '', 'Carry', '', '解釈しないスカラー'),
    ('carryElements', '`CarryElement[]`', '否（空可）', '', '', 'Carry', '', '`WorkingTimes` ほか'),
 ]),
 ('Resource', '担当者 1 人（または 1 つの資源）', [
    ('uid', '整数', '否', 'PK', '', 'Own', 'Resource/UID', '担当者の識別子'),
    ('name', '文字列', '可', '', '', 'Own', 'Resource/Name', '担当者名'),
    ('resourceKind', '整数', '可', '', '', 'Own', 'Resource/Type', '`0` = 材料 / `1` = 作業 / `2` = 費用'),
    ('isCostResource', '真偽', '可', '', '', 'Own', 'Resource/IsCostResource', '費用資源か'),
    ('calendarUid', '整数', '可', 'FK', '`Calendar.uid`', 'Consume', 'Resource/CalendarUID', 'この担当者が使う暦'),
    ('carry', '連想（文字列→文字列）', '否（空可）', '', '', 'Carry', '', '解釈しないスカラー 59'),
    ('carryElements', '`CarryElement[]`', '否（空可）', '', '', 'Carry', '', '行にならなかった子要素 6'),
 ]),
 ('Assignment', 'どの担当者がどのタスクに就くか', [
    ('uid', '整数', '否', 'PK', '', 'Own', 'Assignment/UID', '割当の識別子'),
    ('taskUid', '整数', '可', 'FK', '`Task.uid`', 'Consume', 'Assignment/TaskUID', '就くタスク'),
    ('resourceUid', '整数', '可', 'FK', '`Resource.uid`', 'Consume', 'Assignment/ResourceUID', '就く担当者'),
    ('carry', '連想（文字列→文字列）', '否（空可）', '', '', 'Carry', '', '解釈しないスカラー 58'),
    ('carryElements', '`CarryElement[]`', '否（空可）', '', '', 'Carry', '', '行にならなかった子要素 3'),
 ]),
 ('TaskVisual', 'タスクの見せ方。形・色・名前の置き方', [
    ('taskUid', '整数', '否', 'PK/FK', '`Task.uid`', 'GRS', '', '対象のタスク'),
    ('nameAnchor', '整数（0〜8）', '可', '', '', 'GRS', '', '名前を置く位置（表 T-019）'),
    ('nameAlign', "列挙（`'left'` ほか 3 値）", '可', '', '', 'GRS', '', '名前の揃え'),
    ('shapeKind', '列挙（5 値）', '可', '', '', 'GRS', '', '**描画の形だけを決める。`Task.milestone` を変えない**（表 T-012）'),
    ('milestoneGlyph', '列挙（8 値）', '可', '', '', 'GRS', '', "`shapeKind` が `'milestone'` のときだけ見る"),
    ('fillColor', '文字列', '可（`null` = テーマから解く）', '', '', 'GRS', '', '塗り。**輪郭と同時に透明にできない**（`FR-030`）'),
    ('strokeColor', '文字列', '可（同上）', '', '', 'GRS', '', '輪郭。同上'),
    ('lineWeight', "列挙（`'thin'` ほか 3 値）", '可', '', '', 'GRS', '', '輪郭の太さ'),
 ]),
 ('TaskOrigin', '取り込み元の記録。合流の照合に使う', [
    ('taskUid', '整数', '否', 'PK/FK', '`Task.uid`', 'GRS', '', '対象のタスク。**行が無い = 本ソフトウェア生まれ**'),
    ('sourceProjectUid', '文字列', '可', '', '', 'GRS', '', '取り込み元のプロジェクト'),
    ('sourceUid', '整数', '否', '', '', 'GRS', '', '取り込み元でのタスクの識別子'),
    ('lastSeenImportSeq', '整数', '否', '', '', 'GRS', '', '最後に見た取り込みの通し番号（`MG-13`）'),
    ('importSessionId', '文字列', '可', '', '', 'GRS', '', '取り込み 1 回の識別子'),
 ]),
 ('CommentBox', 'コメントボックス 1 つ。日付と行に留める', [
    ('id', '文字列（UUID）', '否', 'PK', '', 'GRS', '', '注記の識別子'),
    ('leaderShapeKind', '列挙（2 値）', '可', '', '', 'GRS', '', '引き出し線の形'),
    ('text', '文字列', '可', '', '', 'GRS', '', '**本文。「コメント」と略さない**（`U-14`）'),
    ('anchorDate', '日時', '可', '', '', 'GRS', '', '留める日'),
    ('anchorGroupId', '文字列（UUID）', '可', 'FK', '`TaskGroup.id`', 'GRS', '', '留める行'),
    ('anchorTaskUid', '整数', '可', 'FK', '`Task.uid`', 'GRS', '', '留めるタスク'),
    ('anchorPoint', '整数（0〜8）', '可', '', '', 'GRS', '', 'タスクのどこに留めるか'),
    ('bodyOffsetPx', '`{ dx, dy }`', '可', '', '', 'GRS', '', '留めた点から本文までのずれ'),
 ]),
 ('HighlightBox', 'ハイライトボックス 1 つ。日付と行の範囲を囲む', [
    ('id', '文字列（UUID）', '否', 'PK', '', 'GRS', '', '注記の識別子'),
    ('startDate', '日時', '可', '', '', 'GRS', '', '囲む範囲の左端'),
    ('endDate', '日時', '可', '', '', 'GRS', '', '囲む範囲の右端'),
    ('topGroupId', '文字列（UUID）', '可', 'FK', '`TaskGroup.id`', 'GRS', '', '囲む範囲の上端の行'),
    ('bottomGroupId', '文字列（UUID）', '可', 'FK', '`TaskGroup.id`', 'GRS', '', '囲む範囲の下端の行'),
    ('strokeColor', '文字列', '可', '', '', 'GRS', '', '枠の色'),
    ('cornerRadiusPx', '数値', '可', '', '', 'GRS', '', '角の丸み'),
 ]),
 ('CarryElement', '解釈しない要素 1 つを、原形のまま抱える器（自己参照）', [
    ('ordinal', '整数', '否', 'PK', '', 'GRS', '',
     '所有者の中での出現順。**所有者とこれで一意になる。これで元の位置に戻す**'),
    ('name', '文字列', '否', '', '', 'Carry', '', '交換相手での要素名。**綴りを変えない**（`W-9`）'),
    ('fields', '連想（文字列→文字列）', '否（空可）', '', '', 'Carry', '', 'その要素が持つ葉'),
    ('children', '`CarryElement[]`', '否（空可）', '', '', 'Carry', '', '入れ子の子。**深さの上限は定めない**'),
 ]),
]

STAMP = [
 ('revisionStamp', '版数と、最後に書いた者と時刻', [
    ('revision', '整数', '否', '', '', 'GRS', '', '1 ずつ増える。上げる条件は `FR-063`'),
    ('lastEditedBy', '文字列', '否', '', '', 'GRS', '', '最後に書いた者。人か、AI か'),
    ('updatedAt', '文字列（`ISO 8601`・UTC・秒）', '否', '', '', 'GRS', '',
     '最後に書いた時刻。**秒までとする**（透かしと精度を揃える）'),
 ]),
 ('changeLog', '変更の理由。**会話そのものは保存しない**（`FR-066`）', [
    ('revision', '整数', '否', 'PK', '', 'GRS', '', 'どの版に対する理由か'),
    ('editedBy', '文字列', '否', '', '', 'GRS', '', 'その版を書いた者'),
    ('explanation', '文字列', '否', '', '', 'GRS', '', 'なぜそう変えたか（`UC-013`）'),
    ('changedAt', '文字列（`ISO 8601`・UTC・秒）', '否', '', '', 'GRS', '', 'その版の時刻'),
 ]),
]
