# -*- coding: utf-8 -*-
"""Count every British spelling in the tracked tree, by class (CR-730).

change-request/CR-730-one-spelling-american-color-everywhere.md carries the
numbers this prints (section 3) and names this script in section 13.

Usage, from the repository root of a clean tree (it reads `git ls-files`):
    PYTHONIOENCODING=utf-8 python docs/review/british-spelling-survey-cr730.py <out-dir>

<out-dir> must lie OUTSIDE the worktree (OneDrive syncs it, DFC-2312). It gets
hits.tsv (one row per occurrence: path, line, word, sub-word, family, class,
kind). Standard output gets:
  1. the class x family table (section 3.1 of the CR),
  2. the live totals per family (section 3.2),
  3. the distinct-name counts per class,
  4. the public names: GRS JSON schema keys and enum values, MCP tool names,
     Agent API members and commands of table T-107 (classes c and d),
  5. the code-point spellings (String.fromCharCode / fromCodePoint, hex or
     decimal arrays, \\u and \\x escapes, split literals) that spell a word,
  6. the collisions: a British name whose American form is already a token
     of the same file (section 7.3).

Words are matched on SUB-WORDS (camelCase / snake_case / kebab-case split),
so `groupDepthLimitReached` never reads as a British word. The lexer of
tools/rename/lex_spans.mjs (babel, from the node_modules above the tree)
says whether a hit in JS/TS is code, comment, string or regex.
"""
import bisect
import collections
import io
import json
import os
import re
import subprocess
import sys
import tokenize

# family -> full match on a lower-case sub-word
FAMILIES = [
    ('colour', r'.*colour.*'),
    ('centre', r'.*(centre|centring).*'),
    ('grey', r'.*grey.*'),
    ('behaviour', r'.*behaviour.*'),
    ('-our', r'(un|dis)?(neighbour|honour|flavour|favour|labour|humour|rumour|harbour|vapour|'
             r'armour|endeavour|odour|vigour|rigour|savour|parlour)'
             r'(s|ed|ing|able|ably|ite|ites|hood|less|ful)?'),
    ('-ise', r'(un|re|de|non|over|under)?(minim|maxim|normal|summar|recogn|stabil|raster|serial|'
             r'deserial|parameter|local|capital|anonym|canonical|canon|author|general|initial|'
             r'linear|institutional|neutral|optim|quant|random|real|organ|visual|custom|priorit|'
             r'final|synchron|util|categor|special|material|memor|sanit|token|character|digit|'
             r'standard|central|item|penal|harmon|apolog|critic|emphas|colour|recolour|norm|'
             r'equal|regular|vector|binar|discret|factor|modern|optimal|personal|internal|'
             r'external|legal|fertil|steril|sympath|hospital|immun|mobil|symbol|scrutin|fantas|'
             r'subsid|vapor|agon|dramat|publici|theor|jeopard|pressur|patron|terror|polar|motor|'
             r'monopol)is(e|es|ed|ing|er|ers|ation|ations|able)'),
    ('-yse', r'(un|re)?(analys|paralys|catalys|electrolys|dialys)(e|ed|er|ers|ing)'),
    ('-lled', r'(un|re|pre)?(cancel|label|model|travel|level|signal|total|fuel|channel|tunnel|'
              r'dial|marshal|counsel|jewel|equal|initial|rival|shovel|snorkel|spiral|bevel|'
              r'chisel|duel|funnel|grovel|marvel|panel|pencil|quarrel|ravel|unravel|revel|'
              r'swivel|towel|yodel|kennel|libel|barrel|cudgel|enamel|gravel)l(ed|ing|er|ers)'),
    ('-re', r'(centi|milli|kilo)?(metre|litre|fibre|theatre|calibre|mitre|lustre|sombre|spectre|'
            r'meagre|sabre|manoeuvre)(s|d)?'),
    ('licence', r'licenc(e|es|ed|ing)'),
    ('other', r'(catalogue|catalogues|catalogued|programme|programmes|artefact|artefacts|'
              r'judgement|judgements|acknowledgement|acknowledgements|fulfil|fulfils|fulfilment|'
              r'enrol|enrols|enrolment|instalment|skilful|wilful|ageing|defence|offence|pretence|'
              r'practise|practised|spelt|burnt|learnt|dreamt|spilt|spoilt|whilst|amongst|cheque|'
              r'tyre|storey|aluminium|sceptic|sceptical|plough|analogue|focussed|focussing|'
              r'aeroplane|mould|moulded|kerb|draught)'),
    # valid American for a conversation: counted, not changed (CR-730 X-6)
    ('note:dialogue', r'.*dialogue.*'),
]
FAMILIES = [(n, re.compile(rx)) for n, rx in FAMILIES]
NAMES = [n for n, _ in FAMILIES]
HISTORY = ('docs/development-records/', 'change-request/', 'docs/review/')
SAMPLES = 'previous-project-result/'
GEN_HEAD = re.compile(u'GENERATED\\b|\\bGenerated (from|by)\\b|\\bgenerated by\\b|'
                      u'本書は生成物である')
MANUSCRIPT = 'SINGLE SOURCE OF TRUTH'
GUIDES = ('docs/guides/', 'docs/spec/_source/image-to-grs-json-prompt.en.md')
# someone else's names (class k), by path and line; a code token on the line stays ours
THIRD_PARTY = {
    ('src/framework/mcp-relay-server/mcp-relay-server.ts', 70),  # MCP notifications/cancelled
    ('tests/contract/cr-613-seam-3-mcp-relay-server.contract.test.ts', 722),  # the same
    ('docs/development-rules/software-quality-standards-ja.md', 235),  # MITRE
    ('docs/development-rules/usability-principles-ja.md', 400),  # a URL domain
}
JS_EXT = ('.ts', '.tsx', '.mjs', '.js', '.cjs')
BINARY = ('.png', '.xlsx', '.sgra', '.ico', '.woff', '.woff2', '.jpg')
WORD = re.compile(r'[A-Za-z]+')
SUB = re.compile(r'[A-Z]?[a-z]+|[A-Z]+(?![a-z])')


def family_of(sub):
    for name, rx in FAMILIES:
        if rx.fullmatch(sub.lower()):
            return name
    return None


def tracked():
    out = subprocess.run(['git', 'ls-files'], capture_output=True, text=True, encoding='utf-8')
    return [f for f in out.stdout.split('\n') if f and not f.endswith(BINARY) and os.path.isfile(f)]


def read(path):
    with io.open(path, encoding='utf-8', errors='replace', newline='') as h:
        return h.read().replace('\r\n', '\n')


def is_generated(path, text):
    """tools/rename/rename_common.is_generated, widened to the markers the
    generators of this tree print ("Generated from", "generated by"), plus
    dist/ and every JSON under src/ (all of them are `npm run gen` output).
    A .ts file is never generated as a whole: the generators print regions
    INTO hand-written files, and those regions follow `npm run gen`."""
    if path.startswith('dist/') or (path.startswith('src/') and path.endswith('.json')):
        return True
    if path.endswith(('.py', '.ts')):
        return False
    head = '\n'.join(text.split('\n')[:15])[:6000]
    if MANUSCRIPT in head:
        return False
    return bool(GEN_HEAD.search(head))


def lex_js(paths):
    run = subprocess.run(['node', 'tools/rename/lex_spans.mjs', '.'], input=json.dumps(paths),
                         capture_output=True, text=True, encoding='utf-8')
    return json.loads(run.stdout) if run.stdout else {}


def lex_py(text):
    starts = [0]
    for line in text.split('\n'):
        starts.append(starts[-1] + len(line) + 1)
    spans = []
    try:
        for tok in tokenize.generate_tokens(io.StringIO(text).readline):
            if tok.type in (tokenize.COMMENT, tokenize.STRING):
                spans.append([starts[tok.start[0] - 1] + tok.start[1],
                              starts[tok.end[0] - 1] + tok.end[1],
                              'comment' if tok.type == tokenize.COMMENT else 'string'])
    except (tokenize.TokenError, IndentationError, SyntaxError):
        return None
    return sorted(spans)


def kind_at(spans, pos):
    if spans is None:
        return 'unlexed'
    i = bisect.bisect_right([s[0] for s in spans], pos) - 1
    return spans[i][2] if i >= 0 and spans[i][0] <= pos < spans[i][1] else 'code'


def kind_of(path, text, pos, end, spans, line_start):
    if path.endswith(JS_EXT + ('.py',)) and not path.startswith('dist/'):
        return kind_at(spans, pos)
    if path.endswith('.json'):
        key = text[pos - 1:pos] == '"' and re.match(r'"\s*:', text[end:end + 4])
        return 'json-key' if key else 'json-value'
    if path.endswith('.md'):
        return 'md-code' if text[line_start:pos].count('`') % 2 == 1 else 'md-prose'
    return 'text'


def path_class(path, gen):
    if path.startswith(HISTORY):
        return 'l history'
    if path.startswith(SAMPLES):
        return 'l history (previous-project-result)'
    if gen:
        return 'gen ' + path.split('/')[0]
    if path.startswith('sample-schedule/'):
        return 'x sample-schedule (JDG-1732)'
    return None


def live_class(path, kind):
    if path == 'docs/spec/_source/display-words.json':
        return 'a screen words' if kind == 'json-value' else 'b spec names'
    if path.startswith(GUIDES):
        return 'a2 guides and the image prompt'
    if path.startswith('docs/spec/'):
        names = kind == 'json-key' or (kind == 'json-value' and path.endswith(
            ('state-machines.json', 'published-entries.json')))
        return 'b spec names' if names else 'b spec text'
    if path.startswith('src/'):
        return 'e src identifiers' if kind == 'code' else 'f src comments and strings'
    if path.startswith('tests/'):
        return 'g tests'
    return 'h tools, rules, root config'


def survey(files):
    spans_js = lex_js([f for f in files if f.endswith(JS_EXT) and not f.startswith('dist/')])
    rows = []
    for path in files:
        text = read(path)
        gen = is_generated(path, text)
        spans = spans_js.get(path) if path.endswith(JS_EXT) else lex_py(text) if path.endswith('.py') else None
        starts = [0] + [m.end() for m in re.finditer('\n', text)]
        for m in WORD.finditer(text):
            for s in SUB.finditer(m.group(0)):
                fam = family_of(s.group(0))
                if not fam:
                    continue
                pos = m.start() + s.start()
                line = bisect.bisect_right(starts, pos)
                kind = kind_of(path, text, m.start(), m.end(), spans, starts[line - 1])
                cls = path_class(path, gen)
                if cls is None:
                    third = (path, line) in THIRD_PARTY and kind != 'code'
                    cls = 'k third-party' if third else live_class(path, kind)
                rows.append((path, line, m.group(0), s.group(0), fam, cls, kind))
        hist = path.startswith(HISTORY + (SAMPLES,))
        for part in path.split('/'):
            for m in WORD.finditer(part):
                for s in SUB.finditer(m.group(0)):
                    fam = family_of(s.group(0))
                    if fam:
                        rows.append((path, 0, part, s.group(0), fam,
                                     'l history (path)' if hist else 'i path', 'path'))
    return rows


def print_tables(rows):
    table = collections.Counter((r[5], r[4]) for r in rows)
    classes = sorted(set(r[5] for r in rows))
    print('3.1 class x family (British total excludes note:dialogue)')
    print('class\t' + '\t'.join(NAMES) + '\tBritish\tnot-colour')
    for c in classes + ['ALL']:
        v = [sum(table[(k, n)] for k in classes) if c == 'ALL' else table[(c, n)] for n in NAMES]
        print(c + '\t' + '\t'.join(map(str, v)) + '\t%d\t%d' % (sum(v[:-1]), sum(v[1:-1])))
    live = [c for c in classes if c[:2] in ('a ', 'a2', 'b ', 'e ', 'f ', 'g ', 'h ', 'i ')]
    print('\n3.2 live (hand-edited, not history, not excluded) per family')
    for n in NAMES:
        print('%s\t%d' % (n, sum(table[(c, n)] for c in live)))
    print('\n3.3 distinct names (code tokens, JSON keys, spec names, paths) per class')
    names = collections.defaultdict(set)
    files = collections.defaultdict(set)
    for p, _, w, _, fam, c, k in rows:
        if fam == 'note:dialogue':
            continue
        files[c].add(p)
        if k in ('code', 'json-key', 'path') or c == 'b spec names':
            names[(c, fam == 'colour')].add(w)
    for c in classes:
        print('%s\tcolour names %d\tother names %d\tfiles %d' % (
            c, len(names[(c, True)]), len(names[(c, False)]), len(files[c])))


def british_in(word):
    return [s.group(0) for s in SUB.finditer(word) if family_of(s.group(0)) not in (None, 'note:dialogue')]


def print_public_names():
    print('\n4. public names')
    schema = json.loads(read('docs/spec/_source/grs-document.schema.json'))
    keys, values = set(), set()

    def walk(node):
        if isinstance(node, dict):
            for k, v in node.items():
                if k == 'properties' and isinstance(v, dict):
                    keys.update(v.keys())
                if k in ('enum', 'const'):
                    values.update(x for x in (v if isinstance(v, list) else [v]) if isinstance(x, str))
                walk(v)
        elif isinstance(node, list):
            for v in node:
                walk(v)
    walk(schema)
    print('c GRS JSON keys %d, British %s' % (len(keys), sorted(k for k in keys if british_in(k))))
    print('c GRS JSON enum/const values %d, British %s' % (
        len(values), sorted(v for v in values if british_in(v))))
    tools = json.loads(read('src/adapter/mcp-tool-translator/mcp-tool-descriptions.json'))['tools']
    print('d MCP tools %d, British names %s, British words in descriptions %d' % (
        len(tools), [t['name'] for t in tools if british_in(t['name'])],
        sum(len(british_in(w)) for t in tools for w in WORD.findall(t['description']))))
    glossary = read('docs/spec/_assets/tbl-glossary.md')
    members = re.findall(r'^\| ((?:AM|CM)-\d+) \|[^|]*\| `([^`]+)`', glossary, re.M)
    print('d Agent API members and commands (table T-107 AM / CM rows) %d, British %s' % (
        len(members), [m for m in members if british_in(m[1])]))


CODEPOINT_WORD = re.compile(r'colour|centre|grey|behaviour|neighbour|honour|licenc|judgement|'
                            r'programme|spelt|burnt|cancell|labell|travell|analys|'
                            r'(minim|maxim|normal|summar|recogn|organ|serial|initial)is', re.I)


def print_codepoints(files):
    found = []
    call = re.compile(r'from(?:Char|Code)(?:Code|Point)\s*\(([^()]*)\)')
    array = re.compile(r'\[\s*((?:(?:0x[0-9a-fA-F]+|\d{2,3})\s*,\s*){2,}(?:0x[0-9a-fA-F]+|\d{2,3}))\s*,?\s*\]')
    escape = re.compile(r'(?:\\u[0-9a-fA-F]{4}|\\x[0-9a-fA-F]{2}|\\u\{[0-9a-fA-F]+\}|[A-Za-z])+')
    concat = re.compile(r"""(['"`])([A-Za-z]{1,12})\1\s*\+\s*(['"`])([A-Za-z]{1,12})\3""")
    for path in files:
        if not path.endswith(JS_EXT + ('.py',)) or path.startswith('dist/'):
            continue
        text = read(path)
        decoded = []
        for rx in (call, array):
            for m in rx.finditer(text):
                try:
                    decoded.append(''.join(chr(int(p, 16) if p.lower().startswith('0x') else int(p))
                                           for p in re.split(r'[,\s]+', m.group(1)) if p))
                except ValueError:
                    pass
        for m in escape.finditer(text):
            if '\\' in m.group(0):
                decoded.append(re.sub(r'\\u\{([0-9a-fA-F]+)\}|\\u([0-9a-fA-F]{4})|\\x([0-9a-fA-F]{2})',
                                      lambda g: chr(int(g.group(1) or g.group(2) or g.group(3), 16)),
                                      m.group(0)))
        for m in concat.finditer(text):
            if not CODEPOINT_WORD.search(m.group(2)) and not CODEPOINT_WORD.search(m.group(4)):
                decoded.append(m.group(2) + m.group(4))
        found += [(path, s) for s in decoded if CODEPOINT_WORD.search(s)]
    print('\n5. code-point and split-literal spellings of a British word: %d %s' % (len(found), found))


AMERICAN = [('colour', 'color'), ('centring', 'centering'), ('centred', 'centered'),
            ('centres', 'centers'), ('centre', 'center'), ('grey', 'gray'),
            ('behaviour', 'behavior'), ('neighbour', 'neighbor'), ('honour', 'honor'),
            ('flavour', 'flavor'), ('favour', 'favor'), ('licence', 'license'),
            ('judgement', 'judgment'), ('programme', 'program'), ('spelt', 'spelled'),
            ('burnt', 'burned'), ('learnt', 'learned'), ('mitred', 'mitered'),
            ('cancelled', 'canceled'), ('cancelling', 'canceling'), ('labelled', 'labeled'),
            ('travelled', 'traveled'), ('travelling', 'traveling'), ('analysed', 'analyzed'),
            ('analyse', 'analyze')]
ISE = re.compile(r'is(e|es|ed|ing|er|ers|ation|ations|able)$')


def american(word):
    out = []
    for s in re.findall(r'[A-Z]?[a-z]+|[A-Z]+(?![a-z])|[^A-Za-z]+', word):
        low = s.lower()
        new = low
        if s.isalpha() and family_of(s) not in (None, 'note:dialogue'):
            for a, b in AMERICAN:
                if a in new:
                    new = new.replace(a, b)
                    break
            else:
                new = ISE.sub(lambda m: 'iz' + m.group(1), low)
        if new == low:
            out.append(s)
        elif s.isupper():
            out.append(new.upper())
        else:
            out.append(new[0].upper() + new[1:] if s[0].isupper() else new)
    return ''.join(out)


def print_collisions(rows):
    per_file = collections.defaultdict(set)
    for p, _, w, _, fam, c, k in rows:
        if k == 'code' and fam != 'note:dialogue' and c[:2] in ('b ', 'e ', 'g ', 'h '):
            per_file[p].add(w)
    hits = []
    for path, words in sorted(per_file.items()):
        tokens = set(re.findall(r'[A-Za-z_][A-Za-z0-9_]*', read(path)))
        hits += [(path, w, american(w)) for w in sorted(words) if american(w) != w and american(w) in tokens]
    print('\n6. same-file collisions (a British code name whose American form is a token of the file): %d'
          % len(hits))
    for h in hits:
        print('\t'.join(h))


def main():
    out = sys.argv[1]
    os.makedirs(out, exist_ok=True)
    files = tracked()
    rows = survey(files)
    with io.open(os.path.join(out, 'hits.tsv'), 'w', encoding='utf-8', newline='\n') as h:
        h.write('path\tline\tword\tsub\tfamily\tclass\tkind\n')
        for r in rows:
            h.write('\t'.join(map(str, r)) + '\n')
    print_tables(rows)
    print_public_names()
    print_codepoints(files)
    print_collisions(rows)


if __name__ == '__main__':
    main()
