# -*- coding: utf-8 -*-
"""Build the two tables of CR-730 section 7 (items 1 and 2) from the tree.

    PYTHONIOENCODING=utf-8 python docs/review/spelling-map-cr730.py [--root <copy>] [--fresh]

Writes
  docs/review/spelling-keep-cr730.tsv  path line text reason   (section 4: what is never changed)
  docs/review/spelling-map-cr730.tsv   old new kind files count collision
                                       (one row per distinct name or word and kind)
The scan and the spelling rule are those of tools/rename/apply_spelling.py, so
the map holds exactly the tokens the applier will meet. `new` is that rule's
American form (JDG-1924: unanalysed -> unreliable). A rebuild KEEPS a `new` or
a `collision` cell edited by hand for the same `old` (pass --fresh to drop
them). `collision` is "lane-B" when the name collides in at least one file
(its American form is already a token of that file, or a sibling JSON key):
lane B of stage 0 reads those and writes the per-file decisions the applier
takes with --collisions.
Run it again on the frozen tree just before applying, and read the diff of
the map: a new row is a name the tree gained after the map was read.
"""
import argparse
import collections
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(os.path.dirname(HERE), '..', 'tools', 'rename'))
import apply_spelling as sp  # noqa: E402
import rename_common as rc  # noqa: E402

WHOLE = [
    ('docs/development-records/', 'history: ruling verbatims, ledgers, measurements (CR-730 X-1)'),
    ('change-request/', 'history: every CR file (X-1). A drafted CR is written by its own body '
                        'and lands in the new spelling'),
    ('docs/review/', 'history: review records, and the CR-730 tables and survey themselves'),
    ('previous-project-result/', 'history, sample folder names included (X-1)'),
    ('sample-schedule/', 'user sample documents are not rewritten (JDG-1732, X-5)'),
    ('tools/rename/', 'the rename tools hold the British spellings as data'),
    ('dist/', 'generated by npm run build (X-2)'),
    ('LICENSE', 'third-party text (Apache License)'),
    ('NOTICE', 'third-party text'),
    ('package-lock.json', 'third-party package names'),
    ('docs/reference/mspdi/', 'MSPDI-owned names (gitignored; the XSD already says color / center)'),
]
LITERALS = [
    ('*', 'notifications/cancelled', 'Model Context Protocol method name (third party, X-4); '
                                     'the GRS constant CANCELLED on the same line is ours'),
    ('docs/development-rules/software-quality-standards-ja.md', 'MITRE', 'organization name'),
    ('docs/development-rules/usability-principles-ja.md', 'centercentre.com', 'URL domain'),
    ('*', 'dialogue', 'correct American spelling for a conversation (X-6); the rule never '
                      'changes it -- listed so nobody adds it'),
    ('*', '<url>', 'every URL is someone else\'s name'),
]


def first_place(files, lit, only=None):
    for path in files:
        if only and path != only:
            continue
        if not (sp.is_live(path) and os.path.isfile(os.path.join(rc.ROOT, path))):
            continue
        try:
            text, _ = rc.read_text(path)
        except UnicodeDecodeError:
            continue
        at = text.find(lit)
        if at >= 0:
            return path, text.count('\n', 0, at) + 1
    return None, None


def build_keep(files):
    rows = [{'path': p, 'line': '', 'text': '*', 'reason': r} for p, r in WHOLE]
    for path, lit, reason in LITERALS:
        line = ''
        if lit != '<url>':
            where, n = first_place(files, lit, None if path == '*' else path)
            line = '' if where is None else (str(n) if path != '*' else '%s:%d' % (where, n))
        rows.append({'path': path, 'line': line, 'text': lit, 'reason': reason})
    whole = [p for p, _ in WHOLE]
    for stem in sorted(sp.history_components(files, whole)):
        where, n = first_place(files, stem)
        rows.append({'path': '*', 'line': '' if where is None else '%s:%d' % (where, n),
                     'text': stem, 'reason': 'names a history path that is not moved (X-1)'})
    for path in files:
        if not sp.is_live(path) or sp.kept_whole(path, whole):
            continue
        if not os.path.isfile(os.path.join(rc.ROOT, path)):
            continue
        try:
            text, _ = rc.read_text(path)
        except UnicodeDecodeError:
            continue
        for m in sp.URL.finditer(text):
            if any(sp.is_british_token(t.group(0)) for t in sp.TOKEN.finditer(m.group(0))):
                rows.append({'path': path, 'line': str(text.count('\n', 0, m.start()) + 1),
                             'text': m.group(0), 'reason': 'URL (covered by the <url> row; listed)'})
    return rows


def build_map(result, moves, previous, fresh):
    groups = collections.defaultdict(lambda: [set(), 0, None])
    for o in result['occs']:
        g = groups[(o.old, o.kind)]
        g[0].add(o.path)
        g[1] += 1
        g[2] = o.new
    for old, new in moves:
        groups[(old, 'path')] = [set([old]), 1, new]
    colliding = set(old for pairs in result['collisions'].values() for old, _ in pairs)
    rows = []
    for (old, kind), (paths, count, new) in sorted(groups.items(), key=lambda kv: (
            kv[0][1], kv[0][0].lower(), kv[0][0])):
        prev = previous.get(old, {}) if not fresh else {}
        collision = prev.get('collision', '')
        if old in colliding and not collision:
            collision = sp.LANE_B
        rows.append({'old': old, 'new': prev.get('new') or new, 'kind': kind,
                     'files': len(paths), 'count': count, 'collision': collision})
    return rows


def drafted_crs(files):
    out = []
    for path in files:
        if not (path.startswith('change-request/CR-') and path.endswith('.md')):
            continue
        text, _ = rc.read_text(path)
        if u'下書き' not in '\n'.join(text.split('\n')[:4]):  # "draft"
            continue
        n = sum(1 for m in sp.TOKEN.finditer(text) if sp.is_british_token(m.group(0)))
        if n:
            out.append((path, n))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--root')
    ap.add_argument('--fresh', action='store_true')
    args = ap.parse_args()
    if args.root:
        rc.set_root(args.root)
    files = rc.git_files()
    keep = build_keep(files)
    rc.write_tsv(sp.KEEP_TSV, sp.KEEP_HEAD, keep)
    whole, literals, urls = sp.load_keep()
    history = sp.history_components(files, whole)
    result = sp.scan_tree(files, whole, literals, urls, history)
    moves = sp.path_moves(files, whole)
    previous = dict((r['old'], r) for r in rc.read_tsv(sp.MAP_TSV))
    rows = build_map(result, moves, previous, args.fresh)
    rc.write_tsv(sp.MAP_TSV, sp.MAP_HEAD, rows)
    kinds = collections.Counter(r['kind'] for r in rows)
    print('map rows %d: %s' % (len(rows), ', '.join('%s %d' % kv for kv in sorted(kinds.items()))))
    print('distinct old names %d; lane-B rows %d' % (
        len(set(r['old'] for r in rows)), sum(1 for r in rows if r['collision'] == sp.LANE_B)))
    kk = collections.Counter('whole path' if r['text'] == '*' else r['reason'][:40] for r in keep)
    print('keep rows %d: %s' % (len(keep), '; '.join('%s %d' % kv for kv in sorted(kk.items()))))
    print('kept occurrences in live files: %s' % dict(result['kept']))
    for path, n in drafted_crs(files):
        print('drafted CR with British spellings (kept, X-1): %s %d' % (path, n))


if __name__ == '__main__':
    main()
