// DocumentCodec -- the GRS JSON schema (the preamble of table T-220) and the answers read against it.
// @unit      UF-152  (docs/spec/05-07-design.md, table T-075)
// @component DocumentCodec, layer Adapter (table T-062)
// @purity    pure

import { isObject } from './mspdi-codec'

export interface JsonFault {
  readonly at: string
  readonly what: string
}

// <generated -- do not edit by hand>
// Single source of truth:
//   docs/spec/_source/grs-document.schema.json
//     (itself generated by docs/spec/_source/erd_json_to_schema.py from
//      erd.json and docs/spec/_assets/tbl-settings.md)
// Rebuild: npm run gen   ||   npm run gen:check fails on drift.
// see T-220
type JsonSchemaKind =
  | 'null'
  | 'boolean'
  | 'integer'
  | 'number'
  | 'string'
  | 'array'
  | 'object'

interface SchemaNode {
  readonly ref?: string
  readonly type?: readonly JsonSchemaKind[]
  readonly enum?: readonly (null | number | string)[]
  readonly minimum?: number
  readonly maximum?: number
  readonly maxLength?: number
  readonly pattern?: string
  readonly required?: readonly string[]
  readonly closed?: true
  readonly values?: SchemaNode
  readonly properties?: Readonly<Record<string, SchemaNode>>
  readonly items?: SchemaNode
}

const SCHEMA_DEFS: Readonly<Record<string, SchemaNode>> = {
  Project: {
    type: ['object'],
    required: ['id', 'name', 'title', 'subject', 'category', 'company', 'manager', 'author', 'created', 'revision', 'startDate', 'statusDate', 'minutesPerDay', 'minutesPerWeek', 'daysPerMonth', 'weekStartDay', 'calendarUid', 'defaultStartTime', 'defaultFinishTime', 'themeHue', 'parentProgressToleranceDays', 'uidHighWaterMark', 'importSeq', 'carry', 'carryElements', 'outlineBase', 'sourceFormat'],
    closed: true,
    properties: {
      id: {
        type: ['string', 'null'],
        maxLength: 16,
      },
      name: {
        type: ['string', 'null'],
      },
      title: {
        type: ['string', 'null'],
      },
      subject: {
        type: ['string', 'null'],
      },
      category: {
        type: ['string', 'null'],
      },
      company: {
        type: ['string', 'null'],
      },
      manager: {
        type: ['string', 'null'],
      },
      author: {
        type: ['string', 'null'],
      },
      created: {
        ref: 'DateTime',
      },
      revision: {
        type: ['integer', 'null'],
      },
      startDate: {
        ref: 'DateTime',
      },
      statusDate: {
        ref: 'DateTime',
      },
      minutesPerDay: {
        type: ['integer', 'null'],
      },
      minutesPerWeek: {
        type: ['integer', 'null'],
      },
      daysPerMonth: {
        type: ['integer', 'null'],
      },
      weekStartDay: {
        type: ['integer', 'null'],
        minimum: 0,
        maximum: 6,
      },
      calendarUid: {
        type: ['integer', 'null'],
      },
      defaultStartTime: {
        ref: 'Time',
      },
      defaultFinishTime: {
        ref: 'Time',
      },
      themeHue: {
        type: ['integer'],
        minimum: 0,
        maximum: 359,
      },
      parentProgressToleranceDays: {
        type: ['integer'],
        minimum: 0,
      },
      uidHighWaterMark: {
        type: ['integer'],
      },
      importSeq: {
        type: ['integer'],
      },
      carry: {
        ref: 'Carry',
      },
      carryElements: {
        type: ['array'],
        items: {
          ref: 'CarryElement',
        },
      },
      outlineBase: {
        type: ['integer'],
      },
      sourceFormat: {
        enum: ['grs', 'pj12', 'pj15'],
      },
    },
  },
  Task: {
    type: ['object'],
    required: ['uid', 'wbsParentUid', 'wbsOrder', 'name', 'start', 'finish', 'milestone', 'deadline', 'notes', 'calendarUid', 'actualStart', 'stop', 'actualFinish', 'resume', 'resumeValid', 'percentComplete', 'fadeInDays', 'fadeOutDays', 'dependencies', 'carry', 'carryElements'],
    closed: true,
    properties: {
      uid: {
        type: ['integer'],
      },
      wbsParentUid: {
        type: ['integer', 'null'],
      },
      wbsOrder: {
        type: ['integer', 'null'],
      },
      name: {
        type: ['string', 'null'],
      },
      start: {
        ref: 'DateTime',
      },
      finish: {
        ref: 'DateTime',
      },
      milestone: {
        type: ['boolean', 'null'],
      },
      deadline: {
        ref: 'DateTime',
      },
      notes: {
        type: ['string', 'null'],
      },
      calendarUid: {
        type: ['integer', 'null'],
      },
      actualStart: {
        ref: 'DateTime',
      },
      stop: {
        ref: 'DateTime',
      },
      actualFinish: {
        ref: 'DateTime',
      },
      resume: {
        ref: 'DateTime',
      },
      resumeValid: {
        type: ['boolean', 'null'],
      },
      percentComplete: {
        type: ['integer', 'null'],
        minimum: 0,
      },
      fadeInDays: {
        type: ['integer', 'null'],
        minimum: 0,
      },
      fadeOutDays: {
        type: ['integer', 'null'],
        minimum: 0,
      },
      dependencies: {
        type: ['array'],
        items: {
          ref: 'Dependency',
        },
      },
      carry: {
        ref: 'Carry',
      },
      carryElements: {
        type: ['array'],
        items: {
          ref: 'CarryElement',
        },
      },
    },
  },
  Dependency: {
    type: ['object'],
    required: ['predecessorUid', 'linkType', 'lag', 'lagFormat', 'carry', 'carryElements'],
    closed: true,
    properties: {
      predecessorUid: {
        type: ['integer'],
      },
      linkType: {
        type: ['integer'],
        minimum: 0,
        maximum: 3,
      },
      lag: {
        type: ['integer', 'null'],
      },
      lagFormat: {
        type: ['integer', 'null'],
      },
      carry: {
        ref: 'Carry',
      },
      carryElements: {
        type: ['array'],
        items: {
          ref: 'CarryElement',
        },
      },
    },
  },
  TaskGroup: {
    type: ['object'],
    required: ['id', 'parentId', 'label', 'derivedFromTaskUid', 'order', 'treeState', 'editGroup', 'color', 'minHeight'],
    closed: true,
    properties: {
      id: {
        type: ['string'],
      },
      parentId: {
        type: ['string', 'null'],
      },
      label: {
        type: ['string', 'null'],
      },
      derivedFromTaskUid: {
        type: ['integer', 'null'],
      },
      order: {
        type: ['integer'],
      },
      treeState: {
        enum: ['auto', 'collapsed', 'expanded', 'temporarilyExpanded', 'hidden'],
      },
      editGroup: {
        type: ['string', 'null'],
      },
      color: {
        type: ['string', 'null'],
        pattern: '^(?:white|dimgray|lightgray|red|blue|yellow|green|orange|purple|transparent|#[0-9a-fA-F]{6}/(?:#[0-9a-fA-F]{6})?|/#[0-9a-fA-F]{6})$',
      },
      minHeight: {
        type: ['integer', 'null'],
      },
    },
  },
  TaskGroupMember: {
    type: ['object'],
    required: ['taskUid', 'groupId'],
    closed: true,
    properties: {
      taskUid: {
        type: ['integer'],
      },
      groupId: {
        type: ['string'],
      },
    },
  },
  Calendar: {
    type: ['object'],
    required: ['uid', 'name', 'isBaseCalendar', 'baseCalendarUid', 'ordinal', 'carry', 'carryElements', 'weekDays', 'exceptions'],
    closed: true,
    properties: {
      uid: {
        type: ['integer'],
      },
      name: {
        type: ['string', 'null'],
      },
      isBaseCalendar: {
        type: ['boolean', 'null'],
      },
      baseCalendarUid: {
        type: ['integer', 'null'],
      },
      ordinal: {
        type: ['integer'],
      },
      carry: {
        ref: 'Carry',
      },
      carryElements: {
        type: ['array'],
        items: {
          ref: 'CarryElement',
        },
      },
      weekDays: {
        type: ['array'],
        items: {
          ref: 'WeekDay',
        },
      },
      exceptions: {
        type: ['array'],
        items: {
          ref: 'Exception',
        },
      },
    },
  },
  WeekDay: {
    type: ['object'],
    required: ['ordinal', 'dayType', 'dayWorking', 'carry', 'carryElements'],
    closed: true,
    properties: {
      ordinal: {
        type: ['integer'],
      },
      dayType: {
        type: ['integer', 'null'],
        minimum: 1,
        maximum: 7,
      },
      dayWorking: {
        type: ['boolean', 'null'],
      },
      carry: {
        ref: 'Carry',
      },
      carryElements: {
        type: ['array'],
        items: {
          ref: 'CarryElement',
        },
      },
    },
  },
  Exception: {
    type: ['object'],
    required: ['ordinal', 'name', 'fromDate', 'toDate', 'dayWorking', 'recurrenceKind', 'carry', 'carryElements'],
    closed: true,
    properties: {
      ordinal: {
        type: ['integer'],
      },
      name: {
        type: ['string', 'null'],
      },
      fromDate: {
        ref: 'DateTime',
      },
      toDate: {
        ref: 'DateTime',
      },
      dayWorking: {
        type: ['boolean', 'null'],
      },
      recurrenceKind: {
        type: ['integer', 'null'],
        minimum: 1,
        maximum: 9,
      },
      carry: {
        ref: 'Carry',
      },
      carryElements: {
        type: ['array'],
        items: {
          ref: 'CarryElement',
        },
      },
    },
  },
  Resource: {
    type: ['object'],
    required: ['uid', 'name', 'resourceKind', 'isCostResource', 'calendarUid', 'carry', 'carryElements'],
    closed: true,
    properties: {
      uid: {
        type: ['integer'],
      },
      name: {
        type: ['string', 'null'],
      },
      resourceKind: {
        type: ['integer', 'null'],
      },
      isCostResource: {
        type: ['boolean', 'null'],
      },
      calendarUid: {
        type: ['integer', 'null'],
      },
      carry: {
        ref: 'Carry',
      },
      carryElements: {
        type: ['array'],
        items: {
          ref: 'CarryElement',
        },
      },
    },
  },
  Assignment: {
    type: ['object'],
    required: ['uid', 'taskUid', 'resourceUid', 'carry', 'carryElements'],
    closed: true,
    properties: {
      uid: {
        type: ['integer'],
      },
      taskUid: {
        type: ['integer', 'null'],
      },
      resourceUid: {
        type: ['integer', 'null'],
      },
      carry: {
        ref: 'Carry',
      },
      carryElements: {
        type: ['array'],
        items: {
          ref: 'CarryElement',
        },
      },
    },
  },
  TaskVisual: {
    type: ['object'],
    required: ['taskUid', 'shapeKind', 'milestoneGlyph', 'fillColor', 'strokeColor', 'strokeWidthPx'],
    closed: true,
    properties: {
      taskUid: {
        type: ['integer'],
      },
      shapeKind: {
        enum: ['rectangle', 'chevron', 'arrow', 'endpointSpan', 'milestone', null],
      },
      milestoneGlyph: {
        enum: ['circle', 'hexagon', 'pentagon', 'diamond', 'square', 'star', 'triangleUp', 'triangleDown', 'file', 'box', 'floppyDisk', 'cylinder', 'person', 'smile', 'beerMug', null],
      },
      fillColor: {
        type: ['string', 'null'],
        pattern: '^(?:white|black|dimgray|lightgray|red|blue|yellow|green|orange|purple|transparent|#[0-9a-fA-F]{6}/(?:#[0-9a-fA-F]{6})?|/#[0-9a-fA-F]{6})$',
      },
      strokeColor: {
        type: ['string', 'null'],
        pattern: '^(?:white|black|dimgray|lightgray|red|blue|yellow|green|orange|purple|transparent|#[0-9a-fA-F]{6}/(?:#[0-9a-fA-F]{6})?|/#[0-9a-fA-F]{6})$',
      },
      strokeWidthPx: {
        type: ['integer', 'null'],
        minimum: 1,
        maximum: 10,
      },
    },
  },
  TaskOrigin: {
    type: ['object'],
    required: ['taskUid', 'sourceProjectUid', 'sourceUid', 'lastSeenImportSeq', 'importSessionId'],
    closed: true,
    properties: {
      taskUid: {
        type: ['integer'],
      },
      sourceProjectUid: {
        type: ['string', 'null'],
      },
      sourceUid: {
        type: ['integer'],
      },
      lastSeenImportSeq: {
        type: ['integer'],
      },
      importSessionId: {
        type: ['string', 'null'],
      },
    },
  },
  CommentBox: {
    type: ['object'],
    required: ['id', 'leaderShapeKind', 'text', 'anchorDate', 'anchorGroupId', 'bodyOffsetPx', 'strokeColor', 'strokeWidthPx', 'fillColor', 'fillTransparencyPercent', 'textColor'],
    closed: true,
    properties: {
      id: {
        type: ['string'],
      },
      leaderShapeKind: {
        enum: ['calloutBox', 'polyline', null],
      },
      text: {
        type: ['string', 'null'],
      },
      anchorDate: {
        ref: 'DateTime',
      },
      anchorGroupId: {
        type: ['string', 'null'],
      },
      bodyOffsetPx: {
        type: ['object', 'null'],
        required: ['dx', 'dy'],
        closed: true,
        properties: {
          dx: {
            type: ['number'],
          },
          dy: {
            type: ['number'],
          },
        },
      },
      strokeColor: {
        type: ['string', 'null'],
        pattern: '^(?:white|black|dimgray|lightgray|red|blue|yellow|green|orange|purple|#[0-9a-fA-F]{6}/(?:#[0-9a-fA-F]{6})?|/#[0-9a-fA-F]{6})$',
      },
      strokeWidthPx: {
        type: ['integer', 'null'],
      },
      fillColor: {
        type: ['string', 'null'],
        pattern: '^(?:white|black|dimgray|lightgray|red|blue|yellow|green|orange|purple|transparent|#[0-9a-fA-F]{6}/(?:#[0-9a-fA-F]{6})?|/#[0-9a-fA-F]{6})$',
      },
      fillTransparencyPercent: {
        type: ['integer', 'null'],
      },
      textColor: {
        type: ['string', 'null'],
        pattern: '^(?:white|black|dimgray|lightgray|red|blue|yellow|green|orange|purple|#[0-9a-fA-F]{6}/(?:#[0-9a-fA-F]{6})?|/#[0-9a-fA-F]{6})$',
      },
    },
  },
  HighlightBox: {
    type: ['object'],
    required: ['id', 'startDate', 'endDate', 'topGroupId', 'bottomGroupId', 'strokeColor', 'cornerRadiusPx', 'strokeWidthPx', 'fillColor', 'fillTransparencyPercent'],
    closed: true,
    properties: {
      id: {
        type: ['string'],
      },
      startDate: {
        ref: 'DateTime',
      },
      endDate: {
        ref: 'DateTime',
      },
      topGroupId: {
        type: ['string', 'null'],
      },
      bottomGroupId: {
        type: ['string', 'null'],
      },
      strokeColor: {
        type: ['string', 'null'],
        pattern: '^(?:white|black|dimgray|lightgray|red|blue|yellow|green|orange|purple|transparent|#[0-9a-fA-F]{6}/(?:#[0-9a-fA-F]{6})?|/#[0-9a-fA-F]{6})$',
      },
      cornerRadiusPx: {
        type: ['number', 'null'],
      },
      strokeWidthPx: {
        type: ['integer', 'null'],
      },
      fillColor: {
        type: ['string', 'null'],
        pattern: '^(?:white|black|dimgray|lightgray|red|blue|yellow|green|orange|purple|transparent|#[0-9a-fA-F]{6}/(?:#[0-9a-fA-F]{6})?|/#[0-9a-fA-F]{6})$',
      },
      fillTransparencyPercent: {
        type: ['integer', 'null'],
      },
    },
  },
  CarryElement: {
    type: ['object'],
    required: ['ordinal', 'name', 'fields', 'children'],
    closed: true,
    properties: {
      ordinal: {
        type: ['integer'],
      },
      name: {
        type: ['string'],
      },
      fields: {
        type: ['object'],
        values: {
          type: ['string'],
        },
      },
      children: {
        type: ['array'],
        items: {
          ref: 'CarryElement',
        },
      },
    },
  },
  documentStamp: {
    type: ['object'],
    required: ['scheduleUpdatedUtc', 'lastEditedBy', 'settingsUpdatedUtc', 'fileSavedUtc'],
    closed: true,
    properties: {
      scheduleUpdatedUtc: {
        type: ['string'],
      },
      lastEditedBy: {
        type: ['string'],
      },
      settingsUpdatedUtc: {
        type: ['string'],
      },
      fileSavedUtc: {
        type: ['string', 'null'],
      },
    },
  },
  changeLog: {
    type: ['object'],
    required: ['ordinal', 'editedBy', 'explanation', 'changedUtc'],
    closed: true,
    properties: {
      ordinal: {
        type: ['integer'],
      },
      editedBy: {
        type: ['string'],
      },
      explanation: {
        type: ['string'],
      },
      changedUtc: {
        type: ['string'],
      },
    },
  },
  BaselineTask: {
    type: ['object'],
    required: ['uid', 'name', 'start', 'finish', 'milestone'],
    closed: true,
    properties: {
      uid: {
        type: ['integer'],
      },
      name: {
        type: ['string', 'null'],
      },
      start: {
        ref: 'DateTime',
      },
      finish: {
        ref: 'DateTime',
      },
      milestone: {
        type: ['boolean', 'null'],
      },
    },
  },
  Carry: {
    type: ['object'],
    values: {
      type: ['string'],
    },
  },
  DateTime: {
    type: ['string', 'null'],
  },
  Time: {
    type: ['string', 'null'],
    pattern: '^\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?(Z|[+-]\\d{2}:\\d{2})?$',
  },
}

// see T-220, OP-6, PI-2
const GRS_DOCUMENT_SCHEMA: SchemaNode = {
  type: ['object'],
  required: ['schemaVersion', 'schedule', 'documentSettings', 'documentStamp', 'changeLog'],
  closed: true,
  properties: {
    schemaVersion: {
      type: ['string'],
    },
    schedule: {
      type: ['object'],
      required: ['project', 'calendars', 'tasks', 'resources', 'assignments', 'taskGroups', 'taskGroupMembers', 'taskVisuals', 'commentBoxes', 'highlightBoxes', 'taskOrigins', 'baselineTasks'],
      closed: true,
      properties: {
        project: {
          ref: 'Project',
        },
        calendars: {
          type: ['array'],
          items: {
            ref: 'Calendar',
          },
        },
        tasks: {
          type: ['array'],
          items: {
            ref: 'Task',
          },
        },
        resources: {
          type: ['array'],
          items: {
            ref: 'Resource',
          },
        },
        assignments: {
          type: ['array'],
          items: {
            ref: 'Assignment',
          },
        },
        taskGroups: {
          type: ['array'],
          items: {
            ref: 'TaskGroup',
          },
        },
        taskGroupMembers: {
          type: ['array'],
          items: {
            ref: 'TaskGroupMember',
          },
        },
        taskVisuals: {
          type: ['array'],
          items: {
            ref: 'TaskVisual',
          },
        },
        commentBoxes: {
          type: ['array'],
          items: {
            ref: 'CommentBox',
          },
        },
        highlightBoxes: {
          type: ['array'],
          items: {
            ref: 'HighlightBox',
          },
        },
        taskOrigins: {
          type: ['array'],
          items: {
            ref: 'TaskOrigin',
          },
        },
        baselineTasks: {
          type: ['array'],
          items: {
            ref: 'BaselineTask',
          },
        },
      },
    },
    documentSettings: {
      type: ['object'],
      required: ['actualVisible', 'assigneeVisible', 'baselineVisible', 'dateGridLinesVisible', 'dependencyVisible', 'displayScale', 'fitSpanFinish', 'fitSpanFixed', 'fitSpanStart', 'fontScale', 'groupGridLinesVisible', 'levelZeroTreeState', 'percentCompleteVisible', 'pinnedGroupIds', 'planDatesVisible', 'planVisible', 'progressLineVisible', 'progressMarkerVisible', 'rowTitlePanelWidth', 'rowTitlePanelWidthFixed', 'rulerFont', 'rulerHeight', 'scrollDate', 'scrollDayOffset', 'scrollGroupId', 'scrollGroupOffset', 'stackDirection', 'themeMonochrome', 'zoomX', 'zoomY'],
      closed: true,
      properties: {
        actualVisible: {
          type: ['boolean'],
        },
        assigneeVisible: {
          type: ['boolean'],
        },
        baselineVisible: {
          type: ['boolean'],
        },
        dateGridLinesVisible: {
          type: ['boolean'],
        },
        dependencyVisible: {
          type: ['boolean'],
        },
        displayScale: {
          enum: [50, 67, 75, 90, 100, 110, 125, 150, 175, 200],
        },
        fitSpanFinish: {
          type: ['string', 'null'],
        },
        fitSpanFixed: {
          type: ['boolean'],
        },
        fitSpanStart: {
          type: ['string', 'null'],
        },
        fontScale: {
          enum: ['S', 'M', 'L'],
        },
        groupGridLinesVisible: {
          type: ['boolean'],
        },
        levelZeroTreeState: {
          enum: ['auto', 'collapsed'],
        },
        percentCompleteVisible: {
          type: ['boolean'],
        },
        pinnedGroupIds: {
          type: ['array'],
          items: {
            type: ['string'],
          },
        },
        planDatesVisible: {
          type: ['boolean'],
        },
        planVisible: {
          type: ['boolean'],
        },
        progressLineVisible: {
          type: ['boolean'],
        },
        progressMarkerVisible: {
          type: ['boolean'],
        },
        rowTitlePanelWidth: {
          type: ['number'],
        },
        rowTitlePanelWidthFixed: {
          type: ['boolean'],
        },
        rulerFont: {
          type: ['number'],
        },
        rulerHeight: {
          type: ['number'],
        },
        scrollDate: {
          type: ['string', 'null'],
        },
        scrollDayOffset: {
          type: ['number'],
        },
        scrollGroupId: {
          type: ['string', 'null'],
        },
        scrollGroupOffset: {
          type: ['number'],
        },
        stackDirection: {
          enum: ['up', 'down'],
        },
        themeMonochrome: {
          type: ['boolean'],
        },
        zoomX: {
          type: ['number'],
        },
        zoomY: {
          type: ['number'],
        },
      },
    },
    documentStamp: {
      ref: 'documentStamp',
    },
    changeLog: {
      type: ['array'],
      items: {
        ref: 'changeLog',
      },
    },
  },
}

// </generated>

const NOT_A_KEY_THIS_SHAPE_CARRIES = 'is not a key this shape carries'

const A_KEY_THIS_SHAPE_LACKS = 'is missing'

/** @purity pure */
export function fault(at: string, what: string): JsonFault {
  return { at, what }
}

/** @purity pure */
export function isUnknownKeyFault(one: JsonFault): boolean {
  return one.what === NOT_A_KEY_THIS_SHAPE_CARRIES
}

/** @purity pure */
export function isMissingKeyFault(one: JsonFault): boolean {
  return one.what === A_KEY_THIS_SHAPE_LACKS
}

/** @purity pure */
function pointer(at: string, key: string): string {
  return `${at}/${key.replace(/~/g, '~0').replace(/\//g, '~1')}`
}

/** @purity pure */
function jsonTypeHolds(value: unknown, kind: JsonSchemaKind): boolean {
  switch (kind) {
    case 'null':
      return value === null
    case 'boolean':
      return typeof value === 'boolean'
    case 'integer':
      return typeof value === 'number' && Number.isInteger(value)
    case 'number':
      return typeof value === 'number' && Number.isFinite(value)
    case 'string':
      return typeof value === 'string'
    case 'array':
      return Array.isArray(value)
    case 'object':
      return isObject(value)
    default: {
      const unreached: never = kind
      return unreached
    }
  }
}

/** @purity pure */
function jsonTypeOf(value: unknown): string {
  if (value === null) return 'null'
  if (Array.isArray(value)) return 'an array'
  if (typeof value === 'number') return Number.isInteger(value) ? 'an integer' : 'a number'
  if (typeof value === 'string') return 'a string'
  if (typeof value === 'boolean') return 'a boolean'
  if (isObject(value)) return 'an object'
  return typeof value
}

// see T-220, T-017b
/** @purity pure */
function stringFaults(value: string, node: SchemaNode, at: string, out: JsonFault[]): void {
  // TRAP: count code points, as JSON Schema maxLength does; value.length counts UTF-16 units.
  if (node.maxLength !== undefined && [...value].length > node.maxLength) {
    out.push(fault(at, `is longer than the ${node.maxLength} characters allowed`))
  }
  if (node.pattern !== undefined && !new RegExp(node.pattern).test(value)) {
    out.push(fault(at, 'is not spelled as the schema allows'))
  }
}

/** @purity pure */
function collectFaults(
  value: unknown,
  node: SchemaNode,
  at: string,
  out: JsonFault[],
): void {
  if (node.ref !== undefined) {
    const target = SCHEMA_DEFS[node.ref]
    if (target !== undefined) collectFaults(value, target, at, out)
    return
  }

  const kinds = node.type
  if (kinds !== undefined && !kinds.some((kind) => jsonTypeHolds(value, kind))) {
    out.push(fault(at, `expected ${kinds.join(' or ')}, was ${jsonTypeOf(value)}`))
    return
  }

  const members = node.enum
  if (members !== undefined && !(members as readonly unknown[]).includes(value)) {
    out.push(
      fault(at, `is not one of ${members.map((one) => JSON.stringify(one)).join(', ')}`),
    )
    return
  }

  if (typeof value === 'number') {
    if (node.minimum !== undefined && value < node.minimum) {
      out.push(fault(at, `is below the least value allowed, ${node.minimum}`))
    }
    if (node.maximum !== undefined && value > node.maximum) {
      out.push(fault(at, `is above the greatest value allowed, ${node.maximum}`))
    }
  }
  if (typeof value === 'string') stringFaults(value, node, at, out)

  if (isObject(value)) {
    for (const key of node.required ?? []) {
      if (!(key in value)) out.push(fault(pointer(at, key), A_KEY_THIS_SHAPE_LACKS))
    }
    for (const [key, inner] of Object.entries(value)) {
      const child = node.properties?.[key] ?? node.values
      if (child !== undefined) {
        collectFaults(inner, child, pointer(at, key), out)
      } else if (node.closed === true) {
        out.push(fault(pointer(at, key), NOT_A_KEY_THIS_SHAPE_CARRIES))
      }
    }
  }

  const items = node.items
  if (items !== undefined && Array.isArray(value)) {
    value.forEach((element, index) => collectFaults(element, items, `${at}/${index}`, out))
  }
}

/** @purity pure */
export function collectSchemaFaults(value: unknown, out: JsonFault[]): void {
  collectFaults(value, GRS_DOCUMENT_SCHEMA, '', out)
}

// see FR-021, AT-154, AT-155
// WHY: held to the same $defs/Time a GRS JSON read holds the two columns to, so a value moved into a column
// from MSPDI always reads back from the GRS JSON written of it.
/** @purity pure */
export function isTimeText(text: string): boolean {
  const faults: JsonFault[] = []
  collectFaults(text, { ref: TIME_DEFINITION }, '', faults)
  return faults.length === 0
}

const TIME_DEFINITION = 'Time'

/** @purity pure */
export function collectionNamesOfEntity(entity: string): readonly string[] {
  const scheduleNode = GRS_DOCUMENT_SCHEMA.properties?.['schedule']
  const collections = scheduleNode?.properties ?? {}
  return Object.entries(collections)
    .filter(([, node]) => node.items?.ref === entity)
    .map(([name]) => name)
}
