// Converts between GRS JSON text and the document.
// @unit      UF-35   (docs/spec/05-07-design.md, table T-075)
// @component DocumentCodec, layer Adapter (table T-062)
// @purity    pure

import type { Document } from '../../entity/document-model/document/document'
import { clampedSettings } from '../../entity/document-model/document-settings/document-settings'
import { withoutLeadingByteOrderMark } from './mspdi-codec'

export interface JsonFault {
  readonly at: string
  readonly what: string
}

export type JsonRefusalReason = 'RS-25'

export type FormatVersionReading = 'notCompared' | 'known' | 'newerThanKnown'

export type JsonDecoding =
  | {
      readonly ok: true
      readonly document: Document
      readonly clampedCount: number
      readonly formatVersion: FormatVersionReading
      readonly unreadColumns: readonly string[]
    }
  | {
      readonly ok: false
      readonly reason: JsonRefusalReason
      readonly faults: readonly JsonFault[]
    }

// <generated -- do not edit by hand>
// Single source of truth:
//   docs/spec/_source/grs-document.schema.json
//     (itself generated by docs/spec/_source/erd_json_to_schema.py from
//      erd.json and docs/spec/_assets/tbl-settings.md)
// Rebuild: npm run gen   ||   npm run gen:check fails on drift.
// see T-220
type JsonSchemaKind =
  | 'null'
  | 'boolean'
  | 'integer'
  | 'number'
  | 'string'
  | 'array'
  | 'object'

interface SchemaNode {
  readonly ref?: string
  readonly type?: readonly JsonSchemaKind[]
  readonly enum?: readonly (null | string)[]
  readonly minimum?: number
  readonly maximum?: number
  readonly maxLength?: number
  readonly required?: readonly string[]
  readonly closed?: true
  readonly values?: SchemaNode
  readonly properties?: Readonly<Record<string, SchemaNode>>
  readonly items?: SchemaNode
}

const SCHEMA_DEFS: Readonly<Record<string, SchemaNode>> = {
  Project: {
    type: ['object'],
    required: ['id', 'name', 'title', 'subject', 'category', 'company', 'manager', 'author', 'created', 'revision', 'lastSaved', 'startDate', 'statusDate', 'minutesPerDay', 'minutesPerWeek', 'daysPerMonth', 'weekStartDay', 'calendarUid', 'themeHue', 'uidHighWaterMark', 'importSeq', 'carry', 'carryElements', 'outlineBase'],
    closed: true,
    properties: {
      id: {
        type: ['string', 'null'],
        maxLength: 16,
      },
      name: {
        type: ['string', 'null'],
      },
      title: {
        type: ['string', 'null'],
      },
      subject: {
        type: ['string', 'null'],
      },
      category: {
        type: ['string', 'null'],
      },
      company: {
        type: ['string', 'null'],
      },
      manager: {
        type: ['string', 'null'],
      },
      author: {
        type: ['string', 'null'],
      },
      created: {
        type: ['string', 'null'],
      },
      revision: {
        type: ['integer', 'null'],
      },
      lastSaved: {
        type: ['string', 'null'],
      },
      startDate: {
        type: ['string', 'null'],
      },
      statusDate: {
        type: ['string', 'null'],
      },
      minutesPerDay: {
        type: ['integer', 'null'],
      },
      minutesPerWeek: {
        type: ['integer', 'null'],
      },
      daysPerMonth: {
        type: ['integer', 'null'],
      },
      weekStartDay: {
        type: ['integer', 'null'],
        minimum: 0,
        maximum: 6,
      },
      calendarUid: {
        type: ['integer', 'null'],
      },
      themeHue: {
        type: ['integer'],
        minimum: 0,
        maximum: 359,
      },
      uidHighWaterMark: {
        type: ['integer'],
      },
      importSeq: {
        type: ['integer'],
      },
      carry: {
        type: ['object'],
        values: {
          type: ['string'],
        },
      },
      carryElements: {
        type: ['array'],
        items: {
          ref: 'CarryElement',
        },
      },
      outlineBase: {
        type: ['integer'],
      },
    },
  },
  Task: {
    type: ['object'],
    required: ['uid', 'wbsParentUid', 'wbsOrder', 'name', 'start', 'finish', 'milestone', 'deadline', 'notes', 'calendarUid', 'actualStart', 'actualDuration', 'actualFinish', 'resume', 'resumeValid', 'percentComplete', 'fadeInDays', 'fadeOutDays', 'dependencies', 'carry', 'carryElements'],
    closed: true,
    properties: {
      uid: {
        type: ['integer'],
      },
      wbsParentUid: {
        type: ['integer', 'null'],
      },
      wbsOrder: {
        type: ['integer', 'null'],
      },
      name: {
        type: ['string', 'null'],
      },
      start: {
        type: ['string', 'null'],
      },
      finish: {
        type: ['string', 'null'],
      },
      milestone: {
        type: ['boolean', 'null'],
      },
      deadline: {
        type: ['string', 'null'],
      },
      notes: {
        type: ['string', 'null'],
      },
      calendarUid: {
        type: ['integer', 'null'],
      },
      actualStart: {
        type: ['string', 'null'],
      },
      actualDuration: {
        type: ['integer', 'null'],
      },
      actualFinish: {
        type: ['string', 'null'],
      },
      resume: {
        type: ['string', 'null'],
      },
      resumeValid: {
        type: ['boolean', 'null'],
      },
      percentComplete: {
        type: ['integer', 'null'],
        minimum: 0,
      },
      fadeInDays: {
        type: ['integer', 'null'],
        minimum: 0,
      },
      fadeOutDays: {
        type: ['integer', 'null'],
        minimum: 0,
      },
      dependencies: {
        type: ['array'],
        items: {
          ref: 'Dependency',
        },
      },
      carry: {
        type: ['object'],
        values: {
          type: ['string'],
        },
      },
      carryElements: {
        type: ['array'],
        items: {
          ref: 'CarryElement',
        },
      },
    },
  },
  Dependency: {
    type: ['object'],
    required: ['predecessorUid', 'linkType', 'lag', 'lagFormat', 'carry', 'carryElements'],
    closed: true,
    properties: {
      predecessorUid: {
        type: ['integer'],
      },
      linkType: {
        type: ['integer'],
        minimum: 0,
        maximum: 3,
      },
      lag: {
        type: ['integer', 'null'],
      },
      lagFormat: {
        type: ['integer', 'null'],
      },
      carry: {
        type: ['object'],
        values: {
          type: ['string'],
        },
      },
      carryElements: {
        type: ['array'],
        items: {
          ref: 'CarryElement',
        },
      },
    },
  },
  TaskGroup: {
    type: ['object'],
    required: ['id', 'parentId', 'label', 'derivedFromTaskUid', 'order', 'isCollapsed', 'isHidden', 'color', 'height'],
    closed: true,
    properties: {
      id: {
        type: ['string'],
      },
      parentId: {
        type: ['string', 'null'],
      },
      label: {
        type: ['string', 'null'],
      },
      derivedFromTaskUid: {
        type: ['integer', 'null'],
      },
      order: {
        type: ['integer'],
      },
      isCollapsed: {
        type: ['boolean', 'null'],
      },
      isHidden: {
        type: ['boolean', 'null'],
      },
      color: {
        type: ['string', 'null'],
      },
      height: {
        type: ['integer', 'null'],
      },
    },
  },
  TaskGroupMember: {
    type: ['object'],
    required: ['taskUid', 'groupId', 'stackOrder'],
    closed: true,
    properties: {
      taskUid: {
        type: ['integer'],
      },
      groupId: {
        type: ['string'],
      },
      stackOrder: {
        type: ['integer', 'null'],
      },
    },
  },
  Calendar: {
    type: ['object'],
    required: ['uid', 'name', 'isBaseCalendar', 'baseCalendarUid', 'ordinal', 'carry', 'carryElements', 'weekDays', 'exceptions'],
    closed: true,
    properties: {
      uid: {
        type: ['integer'],
      },
      name: {
        type: ['string', 'null'],
      },
      isBaseCalendar: {
        type: ['boolean', 'null'],
      },
      baseCalendarUid: {
        type: ['integer', 'null'],
      },
      ordinal: {
        type: ['integer'],
      },
      carry: {
        type: ['object'],
        values: {
          type: ['string'],
        },
      },
      carryElements: {
        type: ['array'],
        items: {
          ref: 'CarryElement',
        },
      },
      weekDays: {
        type: ['array'],
        items: {
          ref: 'WeekDay',
        },
      },
      exceptions: {
        type: ['array'],
        items: {
          ref: 'Exception',
        },
      },
    },
  },
  WeekDay: {
    type: ['object'],
    required: ['ordinal', 'dayType', 'dayWorking', 'carry', 'carryElements'],
    closed: true,
    properties: {
      ordinal: {
        type: ['integer'],
      },
      dayType: {
        type: ['integer', 'null'],
        minimum: 1,
        maximum: 7,
      },
      dayWorking: {
        type: ['boolean', 'null'],
      },
      carry: {
        type: ['object'],
        values: {
          type: ['string'],
        },
      },
      carryElements: {
        type: ['array'],
        items: {
          ref: 'CarryElement',
        },
      },
    },
  },
  Exception: {
    type: ['object'],
    required: ['ordinal', 'name', 'fromDate', 'toDate', 'dayWorking', 'recurrenceKind', 'carry', 'carryElements'],
    closed: true,
    properties: {
      ordinal: {
        type: ['integer'],
      },
      name: {
        type: ['string', 'null'],
      },
      fromDate: {
        type: ['string', 'null'],
      },
      toDate: {
        type: ['string', 'null'],
      },
      dayWorking: {
        type: ['boolean', 'null'],
      },
      recurrenceKind: {
        type: ['integer', 'null'],
        minimum: 1,
        maximum: 9,
      },
      carry: {
        type: ['object'],
        values: {
          type: ['string'],
        },
      },
      carryElements: {
        type: ['array'],
        items: {
          ref: 'CarryElement',
        },
      },
    },
  },
  Resource: {
    type: ['object'],
    required: ['uid', 'name', 'resourceKind', 'isCostResource', 'calendarUid', 'carry', 'carryElements'],
    closed: true,
    properties: {
      uid: {
        type: ['integer'],
      },
      name: {
        type: ['string', 'null'],
      },
      resourceKind: {
        type: ['integer', 'null'],
      },
      isCostResource: {
        type: ['boolean', 'null'],
      },
      calendarUid: {
        type: ['integer', 'null'],
      },
      carry: {
        type: ['object'],
        values: {
          type: ['string'],
        },
      },
      carryElements: {
        type: ['array'],
        items: {
          ref: 'CarryElement',
        },
      },
    },
  },
  Assignment: {
    type: ['object'],
    required: ['uid', 'taskUid', 'resourceUid', 'carry', 'carryElements'],
    closed: true,
    properties: {
      uid: {
        type: ['integer'],
      },
      taskUid: {
        type: ['integer', 'null'],
      },
      resourceUid: {
        type: ['integer', 'null'],
      },
      carry: {
        type: ['object'],
        values: {
          type: ['string'],
        },
      },
      carryElements: {
        type: ['array'],
        items: {
          ref: 'CarryElement',
        },
      },
    },
  },
  TaskVisual: {
    type: ['object'],
    required: ['taskUid', 'nameAnchor', 'nameAlign', 'shapeKind', 'milestoneGlyph', 'fillColor', 'strokeColor', 'lineWeight'],
    closed: true,
    properties: {
      taskUid: {
        type: ['integer'],
      },
      nameAnchor: {
        type: ['integer', 'null'],
        minimum: 0,
        maximum: 8,
      },
      nameAlign: {
        enum: ['left', 'center', 'right', null],
      },
      shapeKind: {
        enum: ['rectangle', 'chevron', 'arrow', 'endpointSpan', 'milestone', null],
      },
      milestoneGlyph: {
        enum: ['circle', 'hexagon', 'pentagon', 'diamond', 'square', 'star', 'triangleUp', 'triangleDown', 'file', 'box', 'floppyDisk', 'cylinder', 'person', 'smile', 'beerMug', null],
      },
      fillColor: {
        type: ['string', 'null'],
      },
      strokeColor: {
        type: ['string', 'null'],
      },
      lineWeight: {
        enum: ['thin', 'medium', 'thick', null],
      },
    },
  },
  TaskOrigin: {
    type: ['object'],
    required: ['taskUid', 'sourceProjectUid', 'sourceUid', 'lastSeenImportSeq', 'importSessionId'],
    closed: true,
    properties: {
      taskUid: {
        type: ['integer'],
      },
      sourceProjectUid: {
        type: ['string', 'null'],
      },
      sourceUid: {
        type: ['integer'],
      },
      lastSeenImportSeq: {
        type: ['integer'],
      },
      importSessionId: {
        type: ['string', 'null'],
      },
    },
  },
  CommentBox: {
    type: ['object'],
    required: ['id', 'leaderShapeKind', 'text', 'anchorDate', 'anchorGroupId', 'bodyOffsetPx'],
    closed: true,
    properties: {
      id: {
        type: ['string'],
      },
      leaderShapeKind: {
        enum: ['calloutBox', 'polyline', null],
      },
      text: {
        type: ['string', 'null'],
      },
      anchorDate: {
        type: ['string', 'null'],
      },
      anchorGroupId: {
        type: ['string', 'null'],
      },
      bodyOffsetPx: {
        type: ['object', 'null'],
        required: ['dx', 'dy'],
        closed: true,
        properties: {
          dx: {
            type: ['number'],
          },
          dy: {
            type: ['number'],
          },
        },
      },
    },
  },
  HighlightBox: {
    type: ['object'],
    required: ['id', 'startDate', 'endDate', 'topGroupId', 'bottomGroupId', 'strokeColor', 'cornerRadiusPx'],
    closed: true,
    properties: {
      id: {
        type: ['string'],
      },
      startDate: {
        type: ['string', 'null'],
      },
      endDate: {
        type: ['string', 'null'],
      },
      topGroupId: {
        type: ['string', 'null'],
      },
      bottomGroupId: {
        type: ['string', 'null'],
      },
      strokeColor: {
        type: ['string', 'null'],
      },
      cornerRadiusPx: {
        type: ['number', 'null'],
      },
    },
  },
  CarryElement: {
    type: ['object'],
    required: ['ordinal', 'name', 'fields', 'children'],
    closed: true,
    properties: {
      ordinal: {
        type: ['integer'],
      },
      name: {
        type: ['string'],
      },
      fields: {
        type: ['object'],
        values: {
          type: ['string'],
        },
      },
      children: {
        type: ['array'],
        items: {
          ref: 'CarryElement',
        },
      },
    },
  },
  documentStamp: {
    type: ['object'],
    required: ['scheduleUpdatedUtc', 'lastEditedBy', 'settingsUpdatedUtc', 'fileSavedUtc'],
    closed: true,
    properties: {
      scheduleUpdatedUtc: {
        type: ['string'],
      },
      lastEditedBy: {
        type: ['string'],
      },
      settingsUpdatedUtc: {
        type: ['string'],
      },
      fileSavedUtc: {
        type: ['string', 'null'],
      },
    },
  },
  changeLog: {
    type: ['object'],
    required: ['ordinal', 'editedBy', 'explanation', 'changedUtc'],
    closed: true,
    properties: {
      ordinal: {
        type: ['integer'],
      },
      editedBy: {
        type: ['string'],
      },
      explanation: {
        type: ['string'],
      },
      changedUtc: {
        type: ['string'],
      },
    },
  },
  BaselineTask: {
    type: ['object'],
    required: ['uid', 'name', 'start', 'finish', 'milestone'],
    closed: true,
    properties: {
      uid: {
        type: ['integer'],
      },
      name: {
        type: ['string', 'null'],
      },
      start: {
        type: ['string', 'null'],
      },
      finish: {
        type: ['string', 'null'],
      },
      milestone: {
        type: ['boolean', 'null'],
      },
    },
  },
}

// see T-220, OP-6, PI-2
const GRS_DOCUMENT_SCHEMA: SchemaNode = {
  type: ['object'],
  required: ['schemaVersion', 'schedule', 'documentSettings', 'documentStamp', 'changeLog'],
  closed: true,
  properties: {
    schemaVersion: {
      type: ['string'],
    },
    schedule: {
      type: ['object'],
      required: ['project', 'calendars', 'tasks', 'resources', 'assignments', 'taskGroups', 'taskGroupMembers', 'taskVisuals', 'commentBoxes', 'highlightBoxes', 'taskOrigins', 'baselineTasks'],
      closed: true,
      properties: {
        project: {
          ref: 'Project',
        },
        calendars: {
          type: ['array'],
          items: {
            ref: 'Calendar',
          },
        },
        tasks: {
          type: ['array'],
          items: {
            ref: 'Task',
          },
        },
        resources: {
          type: ['array'],
          items: {
            ref: 'Resource',
          },
        },
        assignments: {
          type: ['array'],
          items: {
            ref: 'Assignment',
          },
        },
        taskGroups: {
          type: ['array'],
          items: {
            ref: 'TaskGroup',
          },
        },
        taskGroupMembers: {
          type: ['array'],
          items: {
            ref: 'TaskGroupMember',
          },
        },
        taskVisuals: {
          type: ['array'],
          items: {
            ref: 'TaskVisual',
          },
        },
        commentBoxes: {
          type: ['array'],
          items: {
            ref: 'CommentBox',
          },
        },
        highlightBoxes: {
          type: ['array'],
          items: {
            ref: 'HighlightBox',
          },
        },
        taskOrigins: {
          type: ['array'],
          items: {
            ref: 'TaskOrigin',
          },
        },
        baselineTasks: {
          type: ['array'],
          items: {
            ref: 'BaselineTask',
          },
        },
      },
    },
    documentSettings: {
      type: ['object'],
      properties: {
        actualGap: {
          type: ['integer'],
        },
        actualInitialDuration: {
          type: ['integer'],
        },
        actualMin: {
          type: ['integer'],
        },
        actualOfPlan: {
          type: ['number'],
        },
        actualVisible: {
          type: ['boolean'],
        },
        appHeaderMaxHeight: {
          type: ['integer'],
        },
        arrowHeadOfSpan: {
          type: ['number'],
        },
        arrowHeadOfStroke: {
          type: ['number'],
        },
        assigneeVisible: {
          type: ['boolean'],
        },
        basePlanHeight: {
          type: ['integer'],
        },
        baselineVisible: {
          type: ['boolean'],
        },
        canvasPadding: {
          type: ['integer'],
        },
        carryMaxDepth: {
          type: ['integer'],
        },
        chevronNotchOfHeight: {
          type: ['number'],
        },
        chevronNotchOfWidth: {
          type: ['number'],
        },
        commentBoxPad: {
          type: ['integer'],
        },
        commentBoxWrapUnits: {
          type: ['integer'],
        },
        dateGridLinesVisible: {
          type: ['boolean'],
        },
        dependencyArrowLength: {
          type: ['integer'],
        },
        dependencyLagDefault: {
          type: ['integer'],
        },
        dependencyRunOfArrow: {
          type: ['integer'],
        },
        dependencyVisible: {
          type: ['boolean'],
        },
        dependencyWidth: {
          type: ['number'],
        },
        dualCursor: {
          type: ['object', 'null'],
          properties: {
            date1: {
              type: ['string'],
            },
            date2: {
              type: ['string'],
            },
          },
        },
        dummyOpacity: {
          type: ['number'],
        },
        exportCanvas: {
          type: ['object'],
          properties: {
            width: {
              type: ['integer'],
            },
            height: {
              type: ['integer'],
            },
          },
        },
        exportCanvasHeightCap: {
          type: ['number'],
        },
        fadeHandleHalfPx: {
          type: ['number'],
        },
        fadeHandleStrokePx: {
          type: ['number'],
        },
        fontMin: {
          type: ['integer'],
        },
        fontOfActual: {
          type: ['number'],
        },
        fontScale: {
          enum: ['S', 'M', 'L'],
        },
        fontScaleSizes: {
          type: ['object'],
          properties: {
            L: {
              type: ['integer'],
            },
            M: {
              type: ['integer'],
            },
            S: {
              type: ['integer'],
            },
          },
        },
        groupGridLinesVisible: {
          type: ['boolean'],
        },
        groupLevelOfDetailBase: {
          type: ['number'],
        },
        groupLevelOfDetailRatio: {
          type: ['number'],
        },
        guideCursorMode: {
          enum: ['none', 'crosshair', 'single-vertical'],
        },
        iconHintDelayMs: {
          type: ['integer'],
        },
        importMaxBytes: {
          type: ['integer'],
        },
        importMaxDate: {
          type: ['string'],
        },
        importMaxDepth: {
          type: ['integer'],
        },
        importMaxItems: {
          type: ['integer'],
        },
        importMinDate: {
          type: ['string'],
        },
        labelBaseline: {
          type: ['number'],
        },
        labelCoef: {
          type: ['number'],
        },
        labelGap: {
          type: ['integer'],
        },
        labelHaloOfFont: {
          type: ['number'],
        },
        labelPad: {
          type: ['integer'],
        },
        markerGap: {
          type: ['integer'],
        },
        markerSize: {
          type: ['integer'],
        },
        markerStroke: {
          type: ['number'],
        },
        maxGroupDepth: {
          type: ['integer'],
        },
        milestoneActualDuration: {
          type: ['integer'],
        },
        minShapeWidth: {
          type: ['integer'],
        },
        percentCompleteVisible: {
          type: ['boolean'],
        },
        pinnedGroupIds: {
          type: ['array'],
          items: {
            type: ['string'],
          },
        },
        pinnedRowMax: {
          type: ['integer'],
        },
        planActualGuidePattern: {
          type: ['object'],
          properties: {
            off: {
              type: ['number'],
            },
            on: {
              type: ['number'],
            },
          },
        },
        planActualGuideWeight: {
          type: ['number'],
        },
        planStroke: {
          type: ['integer'],
        },
        planVisible: {
          type: ['boolean'],
        },
        progressLineOverhang: {
          type: ['integer'],
        },
        progressLineVisible: {
          type: ['boolean'],
        },
        progressLineWidth: {
          type: ['number'],
        },
        progressMarkerVisible: {
          type: ['boolean'],
        },
        propertyPanelWidth: {
          type: ['number'],
        },
        pxPerDayAt1x: {
          type: ['number'],
        },
        resumeArmOfMarker: {
          type: ['number'],
        },
        resumeDashOff: {
          type: ['integer'],
        },
        resumeDashOn: {
          type: ['integer'],
        },
        resumeHeadOfMarker: {
          type: ['number'],
        },
        resumeScaleInvalid: {
          type: ['number'],
        },
        rowGap: {
          type: ['integer'],
        },
        rowTitleFont: {
          type: ['integer'],
        },
        rowTitleIndent: {
          type: ['integer'],
        },
        rowTitlePanelWidth: {
          type: ['number'],
        },
        rowTitleTopScale: {
          type: ['number'],
        },
        rulerFont: {
          type: ['number'],
        },
        rulerHeight: {
          type: ['number'],
        },
        rulerLabelBottomPad: {
          type: ['integer'],
        },
        rulerLabelGap: {
          type: ['integer'],
        },
        rulerLabelPad: {
          type: ['integer'],
        },
        rulerTierPxPerDayDay: {
          type: ['number'],
        },
        rulerTierPxPerDayMonth: {
          type: ['number'],
        },
        rulerTierPxPerDayWeek: {
          type: ['number'],
        },
        scrollDate: {
          type: ['string', 'null'],
        },
        scrollDayOffset: {
          type: ['number'],
        },
        scrollGroupId: {
          type: ['string', 'null'],
        },
        scrollGroupOffset: {
          type: ['number'],
        },
        shapeHeightOf: {
          type: ['object'],
          properties: {
            arrow: {
              type: ['number'],
            },
            chevron: {
              type: ['number'],
            },
            endpointSpan: {
              type: ['number'],
            },
            milestone: {
              type: ['number'],
            },
            rectangle: {
              type: ['number'],
            },
          },
        },
        spanDotOfStroke: {
          type: ['number'],
        },
        stackDirection: {
          enum: ['up', 'down'],
        },
        stackGap: {
          type: ['integer'],
        },
        stackSafetyCap: {
          type: ['integer'],
        },
        starInnerOfOuter: {
          type: ['number'],
        },
        taskLevelOfDetailReadablePx: {
          type: ['integer'],
        },
        themeMonochrome: {
          type: ['boolean'],
        },
        themePreference: {
          enum: ['light', 'dark'],
        },
        thinFontScale: {
          type: ['number'],
        },
        thinStrokeMax: {
          type: ['integer'],
        },
        thinStrokeMin: {
          type: ['number'],
        },
        thinStrokeOfPlan: {
          type: ['number'],
        },
        truncateUnits: {
          type: ['integer'],
        },
        zoomX: {
          type: ['number'],
        },
        zoomY: {
          type: ['number'],
        },
      },
    },
    documentStamp: {
      ref: 'documentStamp',
    },
    changeLog: {
      type: ['array'],
      items: {
        ref: 'changeLog',
      },
    },
  },
}

// </generated>

const NOT_A_KEY_THIS_SHAPE_CARRIES = 'is not a key this shape carries'

/** @purity pure */
function fault(at: string, what: string): JsonFault {
  return { at, what }
}

/** @purity pure */
function isUnknownKeyFault(one: JsonFault): boolean {
  return one.what === NOT_A_KEY_THIS_SHAPE_CARRIES
}

/** @purity pure */
function columnOf(at: string): string {
  const last = at.slice(at.lastIndexOf('/') + 1)
  return last.replace(/~1/g, '/').replace(/~0/g, '~')
}

/** @purity pure */
function refusal(faults: readonly JsonFault[]): JsonDecoding {
  return { ok: false, reason: 'RS-25', faults }
}

/** @purity pure */
function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

/** @purity pure */
function pointer(at: string, key: string): string {
  return `${at}/${key.replace(/~/g, '~0').replace(/\//g, '~1')}`
}

/** @purity pure */
function jsonTypeHolds(value: unknown, kind: JsonSchemaKind): boolean {
  switch (kind) {
    case 'null':
      return value === null
    case 'boolean':
      return typeof value === 'boolean'
    case 'integer':
      return typeof value === 'number' && Number.isInteger(value)
    case 'number':
      return typeof value === 'number' && Number.isFinite(value)
    case 'string':
      return typeof value === 'string'
    case 'array':
      return Array.isArray(value)
    case 'object':
      return isObject(value)
    default: {
      const unreached: never = kind
      return unreached
    }
  }
}

/** @purity pure */
function jsonTypeOf(value: unknown): string {
  if (value === null) return 'null'
  if (Array.isArray(value)) return 'an array'
  if (typeof value === 'number') return Number.isInteger(value) ? 'an integer' : 'a number'
  if (typeof value === 'string') return 'a string'
  if (typeof value === 'boolean') return 'a boolean'
  if (isObject(value)) return 'an object'
  return typeof value
}

/** @purity pure */
function collectFaults(
  value: unknown,
  node: SchemaNode,
  at: string,
  out: JsonFault[],
): void {
  if (node.ref !== undefined) {
    const target = SCHEMA_DEFS[node.ref]
    if (target !== undefined) collectFaults(value, target, at, out)
    return
  }

  const kinds = node.type
  if (kinds !== undefined && !kinds.some((kind) => jsonTypeHolds(value, kind))) {
    out.push(fault(at, `expected ${kinds.join(' or ')}, was ${jsonTypeOf(value)}`))
    return
  }

  const members = node.enum
  if (members !== undefined && !(members as readonly unknown[]).includes(value)) {
    out.push(
      fault(at, `is not one of ${members.map((one) => JSON.stringify(one)).join(', ')}`),
    )
    return
  }

  if (typeof value === 'number') {
    if (node.minimum !== undefined && value < node.minimum) {
      out.push(fault(at, `is below the least value allowed, ${node.minimum}`))
    }
    if (node.maximum !== undefined && value > node.maximum) {
      out.push(fault(at, `is above the greatest value allowed, ${node.maximum}`))
    }
  }
  if (
    typeof value === 'string' &&
    node.maxLength !== undefined &&
    value.length > node.maxLength
  ) {
    out.push(fault(at, `is longer than the ${node.maxLength} characters allowed`))
  }

  if (isObject(value)) {
    for (const key of node.required ?? []) {
      if (!(key in value)) out.push(fault(pointer(at, key), 'is missing'))
    }
    for (const [key, inner] of Object.entries(value)) {
      const child = node.properties?.[key] ?? node.values
      if (child !== undefined) {
        collectFaults(inner, child, pointer(at, key), out)
      } else if (node.closed === true) {
        out.push(fault(pointer(at, key), NOT_A_KEY_THIS_SHAPE_CARRIES))
      }
    }
  }

  const items = node.items
  if (items !== undefined && Array.isArray(value)) {
    value.forEach((element, index) => collectFaults(element, items, `${at}/${index}`, out))
  }
}

/** @purity pure */
function formatVersionReading(
  schemaVersion: string,
  greatestKnownSchemaVersion: string | undefined,
): FormatVersionReading {
  if (greatestKnownSchemaVersion === undefined) return 'notCompared'
  return schemaVersion > greatestKnownSchemaVersion ? 'newerThanKnown' : 'known'
}

// see FR-023, FR-073, OP-7
/** @purity pure */
export function documentFromJson(
  text: string,
  greatestKnownSchemaVersion?: string,
): JsonDecoding {
  let parsed: unknown
  try {
    parsed = JSON.parse(withoutLeadingByteOrderMark(text))
  } catch (why) {
    return refusal([
      fault('', `not JSON: ${why instanceof Error ? why.message : String(why)}`),
    ])
  }

  const declared = isObject(parsed) ? parsed['schemaVersion'] : undefined
  const formatVersion = formatVersionReading(
    typeof declared === 'string' ? declared : '',
    greatestKnownSchemaVersion,
  )

  const faults: JsonFault[] = []
  collectFaults(parsed, GRS_DOCUMENT_SCHEMA, '', faults)
  const isNewer = formatVersion === 'newerThanKnown'
  const refusing = isNewer ? faults.filter((one) => !isUnknownKeyFault(one)) : faults
  if (refusing.length > 0) return refusal(refusing)
  const unreadColumns = isNewer
    ? [...new Set(faults.filter(isUnknownKeyFault).map((one) => columnOf(one.at)))]
    : []

  // TRAP: a reader before OP-6 may find documentSettings keys missing despite this cast.
  const read = parsed as unknown as Document

  const clamp = clampedSettings(read.documentSettings)
  if (clamp.clamped.length === 0) {
    return { ok: true, document: read, clampedCount: 0, formatVersion, unreadColumns }
  }
  return {
    ok: true,
    document: { ...read, documentSettings: clamp.settings },
    clampedCount: clamp.clamped.length,
    formatVersion,
    unreadColumns,
  }
}

// see FR-024
/** @purity pure */
export function jsonFromDocument(document: Document): string {
  return JSON.stringify(document, null, 1) + '\n'
}
