// DocumentCodec -- the GRS JSON half.
//
// @unit      UF-35   (docs/spec/05-07-design.md, table T-075)
// @component DocumentCodec, layer Adapter (table T-062)
// @purity    pure
//
// Converts between `GRS JSON` and the document (FR-024).
//
// Judging the content is ValidateImportedDocument's (CP-13). This file answers
// only whether the text is a GRS JSON document at all, which has to come first
// because the validator takes a `Document`. The leading byte order mark is
// dropped here (FR-023), because nothing past the parser could still do it.
//
// The generated schema runs here and only here, on the road that reads
// `GRS JSON` (table T-220's preamble). It is not run on the MSPDI road, where
// the codec builds the document itself and would only inspect its own output.

import type { Document } from '../../entity/document-model/document/document'
import { clampedSettings } from '../../entity/document-model/document-settings/document-settings'
import { withoutLeadingByteOrderMark } from './mspdi-codec'

/** Why a text could not be read as a document. */
export interface JsonFault {
  /** Where, as a JSON pointer; `''` names the whole text when no item can be named (NT-1). */
  readonly at: string
  readonly what: string
}

/**
 * The row of table T-233 a refusal from here carries, named here so the shell
 * does not guess. It rides on the decoding rather than on each `JsonFault`,
 * which would repeat one row per item.
 *
 * A text that is not JSON at all carries RS-25 too: table T-233 has no row for
 * it, RS-11 .. RS-13 belong to OP-12's dispatch, and inventing a row is not
 * this file's.
 */
export type JsonRefusalReason = 'RS-25'

/**
 * FR-073's judgement about the format version of the text that was read.
 *
 * `newerThanKnown` is not a refusal and must never become one (FR-073): the
 * decoding stays `ok: true`, and the telling (RS-48) is the caller's.
 *
 * `notCompared` comes back when no version was handed in. It is not spelled
 * `known`, so an uncompared document is never reported as readable; OP-7 sends
 * every open to FR-073, so a caller that gets it owes the version.
 */
export type FormatVersionReading = 'notCompared' | 'known' | 'newerThanKnown'

export type JsonDecoding =
  | {
      readonly ok: true
      readonly document: Document
      /**
       * How many settings keys `clampedSettings` moved; `0` when none. A count
       * and not a list, because no surface shows which keys moved (NT-5).
       * Raising the notice is the caller's.
       */
      readonly clampedCount: number
      /**
       * OP-7 of table T-024a. On the decoding rather than a separate call, so
       * every road that reads `GRS JSON` gets the same judgement.
       */
      readonly formatVersion: FormatVersionReading
      /**
       * The unread columns FR-073 has shown, by distinct name in the order the
       * document first carries each. Empty unless `formatVersion` is
       * `newerThanKnown`: in a known version an unknown key is RS-25's refusal.
       * Names rather than places, because a column stands on every row that
       * carries it. The keys themselves stay on the returned document, which is
       * what carries them back out.
       *
       * No row spells this list's shape (searched FR-073, FR-022, tables T-103,
       * T-233, T-064).
       */
      readonly unreadColumns: readonly string[]
    }
  | {
      readonly ok: false
      readonly reason: JsonRefusalReason
      readonly faults: readonly JsonFault[]
    }

// <generated -- do not edit by hand>
// Single source of truth:
//   docs/spec/_source/grs-document.schema.json
//     (itself generated by docs/spec/_source/erd_json_to_schema.py from
//      erd.json and docs/spec/_assets/tbl-settings.md)
// Rebuild: npm run gen   ||   npm run gen:check fails on drift.
/**
 * Every `type` the manuscript actually writes.
 *
 * ⭐ Measured, not enumerated: `jsonTypeHolds` below switches over this
 * union with a `never` floor, so a type the manuscript grows is a compile
 * error in the walker rather than a rule that is quietly skipped.
 */
type JsonSchemaKind =
  | 'null'
  | 'boolean'
  | 'integer'
  | 'number'
  | 'string'
  | 'array'
  | 'object'

/**
 * The schema of `GRS JSON`, as the walker below reads it.
 *
 * ⭐ ONE NODE PER SCHEMA NODE. `ref` names a member of SCHEMA_DEFS and
 * stands alone; `closed` is `additionalProperties: false`; `values` is
 * `additionalProperties` given a shape (the `carry` maps).
 */
interface SchemaNode {
  readonly ref?: string
  readonly type?: readonly JsonSchemaKind[]
  readonly enum?: readonly (null | string)[]
  readonly minimum?: number
  readonly maximum?: number
  readonly maxLength?: number
  readonly required?: readonly string[]
  readonly closed?: true
  readonly values?: SchemaNode
  readonly properties?: Readonly<Record<string, SchemaNode>>
  readonly items?: SchemaNode
}

/** The `$defs` of the manuscript, by the name a `ref` gives. */
const SCHEMA_DEFS: Readonly<Record<string, SchemaNode>> = {
  Project: {
    type: ['object'],
    required: ['id', 'name', 'title', 'subject', 'category', 'company', 'manager', 'author', 'created', 'revision', 'lastSaved', 'startDate', 'statusDate', 'minutesPerDay', 'minutesPerWeek', 'daysPerMonth', 'weekStartDay', 'calendarUid', 'themeHue', 'uidHighWaterMark', 'importSeq', 'carry', 'carryElements', 'outlineBase'],
    closed: true,
    properties: {
      id: {
        type: ['string', 'null'],
        maxLength: 16,
      },
      name: {
        type: ['string', 'null'],
      },
      title: {
        type: ['string', 'null'],
      },
      subject: {
        type: ['string', 'null'],
      },
      category: {
        type: ['string', 'null'],
      },
      company: {
        type: ['string', 'null'],
      },
      manager: {
        type: ['string', 'null'],
      },
      author: {
        type: ['string', 'null'],
      },
      created: {
        type: ['string', 'null'],
      },
      revision: {
        type: ['integer', 'null'],
      },
      lastSaved: {
        type: ['string', 'null'],
      },
      startDate: {
        type: ['string', 'null'],
      },
      statusDate: {
        type: ['string', 'null'],
      },
      minutesPerDay: {
        type: ['integer', 'null'],
      },
      minutesPerWeek: {
        type: ['integer', 'null'],
      },
      daysPerMonth: {
        type: ['integer', 'null'],
      },
      weekStartDay: {
        type: ['integer', 'null'],
        minimum: 0,
        maximum: 6,
      },
      calendarUid: {
        type: ['integer', 'null'],
      },
      themeHue: {
        type: ['integer'],
        minimum: 0,
        maximum: 359,
      },
      uidHighWaterMark: {
        type: ['integer'],
      },
      importSeq: {
        type: ['integer'],
      },
      carry: {
        type: ['object'],
        values: {
          type: ['string'],
        },
      },
      carryElements: {
        type: ['array'],
        items: {
          ref: 'CarryElement',
        },
      },
      outlineBase: {
        type: ['integer'],
      },
    },
  },
  Task: {
    type: ['object'],
    required: ['uid', 'wbsParentUid', 'wbsOrder', 'name', 'start', 'finish', 'milestone', 'deadline', 'notes', 'calendarUid', 'actualStart', 'actualDuration', 'actualFinish', 'resume', 'resumeValid', 'percentComplete', 'fadeInDays', 'fadeOutDays', 'dependencies', 'carry', 'carryElements'],
    closed: true,
    properties: {
      uid: {
        type: ['integer'],
      },
      wbsParentUid: {
        type: ['integer', 'null'],
      },
      wbsOrder: {
        type: ['integer', 'null'],
      },
      name: {
        type: ['string', 'null'],
      },
      start: {
        type: ['string', 'null'],
      },
      finish: {
        type: ['string', 'null'],
      },
      milestone: {
        type: ['boolean', 'null'],
      },
      deadline: {
        type: ['string', 'null'],
      },
      notes: {
        type: ['string', 'null'],
      },
      calendarUid: {
        type: ['integer', 'null'],
      },
      actualStart: {
        type: ['string', 'null'],
      },
      actualDuration: {
        type: ['integer', 'null'],
      },
      actualFinish: {
        type: ['string', 'null'],
      },
      resume: {
        type: ['string', 'null'],
      },
      resumeValid: {
        type: ['boolean', 'null'],
      },
      percentComplete: {
        type: ['integer', 'null'],
        minimum: 0,
      },
      fadeInDays: {
        type: ['integer', 'null'],
        minimum: 0,
      },
      fadeOutDays: {
        type: ['integer', 'null'],
        minimum: 0,
      },
      dependencies: {
        type: ['array'],
        items: {
          ref: 'Dependency',
        },
      },
      carry: {
        type: ['object'],
        values: {
          type: ['string'],
        },
      },
      carryElements: {
        type: ['array'],
        items: {
          ref: 'CarryElement',
        },
      },
    },
  },
  Dependency: {
    type: ['object'],
    required: ['predecessorUid', 'linkType', 'lag', 'lagFormat', 'carry', 'carryElements'],
    closed: true,
    properties: {
      predecessorUid: {
        type: ['integer'],
      },
      linkType: {
        type: ['integer'],
        minimum: 0,
        maximum: 3,
      },
      lag: {
        type: ['integer', 'null'],
      },
      lagFormat: {
        type: ['integer', 'null'],
      },
      carry: {
        type: ['object'],
        values: {
          type: ['string'],
        },
      },
      carryElements: {
        type: ['array'],
        items: {
          ref: 'CarryElement',
        },
      },
    },
  },
  TaskGroup: {
    type: ['object'],
    required: ['id', 'parentId', 'label', 'derivedFromTaskUid', 'order', 'isCollapsed', 'isHidden', 'color', 'height'],
    closed: true,
    properties: {
      id: {
        type: ['string'],
      },
      parentId: {
        type: ['string', 'null'],
      },
      label: {
        type: ['string', 'null'],
      },
      derivedFromTaskUid: {
        type: ['integer', 'null'],
      },
      order: {
        type: ['integer'],
      },
      isCollapsed: {
        type: ['boolean', 'null'],
      },
      isHidden: {
        type: ['boolean', 'null'],
      },
      color: {
        type: ['string', 'null'],
      },
      height: {
        type: ['integer', 'null'],
      },
    },
  },
  TaskGroupMember: {
    type: ['object'],
    required: ['taskUid', 'groupId', 'stackOrder'],
    closed: true,
    properties: {
      taskUid: {
        type: ['integer'],
      },
      groupId: {
        type: ['string'],
      },
      stackOrder: {
        type: ['integer', 'null'],
      },
    },
  },
  Calendar: {
    type: ['object'],
    required: ['uid', 'name', 'isBaseCalendar', 'baseCalendarUid', 'ordinal', 'carry', 'carryElements', 'weekDays', 'exceptions'],
    closed: true,
    properties: {
      uid: {
        type: ['integer'],
      },
      name: {
        type: ['string', 'null'],
      },
      isBaseCalendar: {
        type: ['boolean', 'null'],
      },
      baseCalendarUid: {
        type: ['integer', 'null'],
      },
      ordinal: {
        type: ['integer'],
      },
      carry: {
        type: ['object'],
        values: {
          type: ['string'],
        },
      },
      carryElements: {
        type: ['array'],
        items: {
          ref: 'CarryElement',
        },
      },
      weekDays: {
        type: ['array'],
        items: {
          ref: 'WeekDay',
        },
      },
      exceptions: {
        type: ['array'],
        items: {
          ref: 'Exception',
        },
      },
    },
  },
  WeekDay: {
    type: ['object'],
    required: ['ordinal', 'dayType', 'dayWorking', 'carry', 'carryElements'],
    closed: true,
    properties: {
      ordinal: {
        type: ['integer'],
      },
      dayType: {
        type: ['integer', 'null'],
        minimum: 1,
        maximum: 7,
      },
      dayWorking: {
        type: ['boolean', 'null'],
      },
      carry: {
        type: ['object'],
        values: {
          type: ['string'],
        },
      },
      carryElements: {
        type: ['array'],
        items: {
          ref: 'CarryElement',
        },
      },
    },
  },
  Exception: {
    type: ['object'],
    required: ['ordinal', 'name', 'fromDate', 'toDate', 'dayWorking', 'recurrenceKind', 'carry', 'carryElements'],
    closed: true,
    properties: {
      ordinal: {
        type: ['integer'],
      },
      name: {
        type: ['string', 'null'],
      },
      fromDate: {
        type: ['string', 'null'],
      },
      toDate: {
        type: ['string', 'null'],
      },
      dayWorking: {
        type: ['boolean', 'null'],
      },
      recurrenceKind: {
        type: ['integer', 'null'],
        minimum: 1,
        maximum: 9,
      },
      carry: {
        type: ['object'],
        values: {
          type: ['string'],
        },
      },
      carryElements: {
        type: ['array'],
        items: {
          ref: 'CarryElement',
        },
      },
    },
  },
  Resource: {
    type: ['object'],
    required: ['uid', 'name', 'resourceKind', 'isCostResource', 'calendarUid', 'carry', 'carryElements'],
    closed: true,
    properties: {
      uid: {
        type: ['integer'],
      },
      name: {
        type: ['string', 'null'],
      },
      resourceKind: {
        type: ['integer', 'null'],
      },
      isCostResource: {
        type: ['boolean', 'null'],
      },
      calendarUid: {
        type: ['integer', 'null'],
      },
      carry: {
        type: ['object'],
        values: {
          type: ['string'],
        },
      },
      carryElements: {
        type: ['array'],
        items: {
          ref: 'CarryElement',
        },
      },
    },
  },
  Assignment: {
    type: ['object'],
    required: ['uid', 'taskUid', 'resourceUid', 'carry', 'carryElements'],
    closed: true,
    properties: {
      uid: {
        type: ['integer'],
      },
      taskUid: {
        type: ['integer', 'null'],
      },
      resourceUid: {
        type: ['integer', 'null'],
      },
      carry: {
        type: ['object'],
        values: {
          type: ['string'],
        },
      },
      carryElements: {
        type: ['array'],
        items: {
          ref: 'CarryElement',
        },
      },
    },
  },
  TaskVisual: {
    type: ['object'],
    required: ['taskUid', 'nameAnchor', 'nameAlign', 'shapeKind', 'milestoneGlyph', 'fillColor', 'strokeColor', 'lineWeight'],
    closed: true,
    properties: {
      taskUid: {
        type: ['integer'],
      },
      nameAnchor: {
        type: ['integer', 'null'],
        minimum: 0,
        maximum: 8,
      },
      nameAlign: {
        enum: ['left', 'center', 'right', null],
      },
      shapeKind: {
        enum: ['rectangle', 'chevron', 'arrow', 'endpointSpan', 'milestone', null],
      },
      milestoneGlyph: {
        enum: ['circle', 'hexagon', 'pentagon', 'diamond', 'square', 'star', 'triangleUp', 'triangleDown', 'file', 'box', 'floppyDisk', 'cylinder', 'person', 'smile', 'beerMug', null],
      },
      fillColor: {
        type: ['string', 'null'],
      },
      strokeColor: {
        type: ['string', 'null'],
      },
      lineWeight: {
        enum: ['thin', 'medium', 'thick', null],
      },
    },
  },
  TaskOrigin: {
    type: ['object'],
    required: ['taskUid', 'sourceProjectUid', 'sourceUid', 'lastSeenImportSeq', 'importSessionId'],
    closed: true,
    properties: {
      taskUid: {
        type: ['integer'],
      },
      sourceProjectUid: {
        type: ['string', 'null'],
      },
      sourceUid: {
        type: ['integer'],
      },
      lastSeenImportSeq: {
        type: ['integer'],
      },
      importSessionId: {
        type: ['string', 'null'],
      },
    },
  },
  CommentBox: {
    type: ['object'],
    required: ['id', 'leaderShapeKind', 'text', 'anchorDate', 'anchorGroupId', 'bodyOffsetPx'],
    closed: true,
    properties: {
      id: {
        type: ['string'],
      },
      leaderShapeKind: {
        enum: ['calloutBox', 'polyline', null],
      },
      text: {
        type: ['string', 'null'],
      },
      anchorDate: {
        type: ['string', 'null'],
      },
      anchorGroupId: {
        type: ['string', 'null'],
      },
      bodyOffsetPx: {
        type: ['object', 'null'],
        required: ['dx', 'dy'],
        closed: true,
        properties: {
          dx: {
            type: ['number'],
          },
          dy: {
            type: ['number'],
          },
        },
      },
    },
  },
  HighlightBox: {
    type: ['object'],
    required: ['id', 'startDate', 'endDate', 'topGroupId', 'bottomGroupId', 'strokeColor', 'cornerRadiusPx'],
    closed: true,
    properties: {
      id: {
        type: ['string'],
      },
      startDate: {
        type: ['string', 'null'],
      },
      endDate: {
        type: ['string', 'null'],
      },
      topGroupId: {
        type: ['string', 'null'],
      },
      bottomGroupId: {
        type: ['string', 'null'],
      },
      strokeColor: {
        type: ['string', 'null'],
      },
      cornerRadiusPx: {
        type: ['number', 'null'],
      },
    },
  },
  CarryElement: {
    type: ['object'],
    required: ['ordinal', 'name', 'fields', 'children'],
    closed: true,
    properties: {
      ordinal: {
        type: ['integer'],
      },
      name: {
        type: ['string'],
      },
      fields: {
        type: ['object'],
        values: {
          type: ['string'],
        },
      },
      children: {
        type: ['array'],
        items: {
          ref: 'CarryElement',
        },
      },
    },
  },
  documentStamp: {
    type: ['object'],
    required: ['scheduleUpdatedUtc', 'lastEditedBy', 'settingsUpdatedUtc', 'fileSavedUtc'],
    closed: true,
    properties: {
      scheduleUpdatedUtc: {
        type: ['string'],
      },
      lastEditedBy: {
        type: ['string'],
      },
      settingsUpdatedUtc: {
        type: ['string'],
      },
      fileSavedUtc: {
        type: ['string', 'null'],
      },
    },
  },
  changeLog: {
    type: ['object'],
    required: ['ordinal', 'editedBy', 'explanation', 'changedUtc'],
    closed: true,
    properties: {
      ordinal: {
        type: ['integer'],
      },
      editedBy: {
        type: ['string'],
      },
      explanation: {
        type: ['string'],
      },
      changedUtc: {
        type: ['string'],
      },
    },
  },
  BaselineTask: {
    type: ['object'],
    required: ['uid', 'name', 'start', 'finish', 'milestone'],
    closed: true,
    properties: {
      uid: {
        type: ['integer'],
      },
      name: {
        type: ['string', 'null'],
      },
      start: {
        type: ['string', 'null'],
      },
      finish: {
        type: ['string', 'null'],
      },
      milestone: {
        type: ['boolean', 'null'],
      },
    },
  },
}

/**
 * The document root.
 *
 * ⛔ `documentSettings` carries neither `required` nor `closed`, here or
 * anywhere below it: the preamble of table T-220 forbids both on that
 * group (MUST NOT) because `OP-6` of table T-024a has the reader fill a
 * missing setting with its default and KEEP a key it does not know.
 *
 * ⛔ It carries no bound either -- no `minimum`, `maximum` or `maxLength`.
 * The same preamble allows that group the type and the enumeration only
 * (MUST) and forbids refusing a value for being out of bounds (MUST NOT),
 * because the range is the work of `clampedSettings` (`PI-2` of table
 * T-064), which moves such a value into range rather than rejecting it.
 * ⚠️ Refusing here would shut a whole document out over one display key.
 *
 * ⛔ AND NOBODY CALLS `clampedSettings` YET. It is exported from
 * entity/document-model/document-settings, and outside its own unit tests
 * the call sites in src/ number ZERO -- so an out-of-bounds setting is
 * now neither refused here nor clamped anywhere. ⚠️ The manuscript does
 * not say on which road the call belongs, so the wiring is deliberately
 * NOT guessed at here; it needs a ruling before it can be written.
 */
const GRS_DOCUMENT_SCHEMA: SchemaNode = {
  type: ['object'],
  required: ['schemaVersion', 'schedule', 'documentSettings', 'documentStamp', 'changeLog'],
  closed: true,
  properties: {
    schemaVersion: {
      type: ['string'],
    },
    schedule: {
      type: ['object'],
      required: ['project', 'calendars', 'tasks', 'resources', 'assignments', 'taskGroups', 'taskGroupMembers', 'taskVisuals', 'commentBoxes', 'highlightBoxes', 'taskOrigins', 'baselineTasks'],
      closed: true,
      properties: {
        project: {
          ref: 'Project',
        },
        calendars: {
          type: ['array'],
          items: {
            ref: 'Calendar',
          },
        },
        tasks: {
          type: ['array'],
          items: {
            ref: 'Task',
          },
        },
        resources: {
          type: ['array'],
          items: {
            ref: 'Resource',
          },
        },
        assignments: {
          type: ['array'],
          items: {
            ref: 'Assignment',
          },
        },
        taskGroups: {
          type: ['array'],
          items: {
            ref: 'TaskGroup',
          },
        },
        taskGroupMembers: {
          type: ['array'],
          items: {
            ref: 'TaskGroupMember',
          },
        },
        taskVisuals: {
          type: ['array'],
          items: {
            ref: 'TaskVisual',
          },
        },
        commentBoxes: {
          type: ['array'],
          items: {
            ref: 'CommentBox',
          },
        },
        highlightBoxes: {
          type: ['array'],
          items: {
            ref: 'HighlightBox',
          },
        },
        taskOrigins: {
          type: ['array'],
          items: {
            ref: 'TaskOrigin',
          },
        },
        baselineTasks: {
          type: ['array'],
          items: {
            ref: 'BaselineTask',
          },
        },
      },
    },
    documentSettings: {
      type: ['object'],
      properties: {
        actualGap: {
          type: ['integer'],
        },
        actualInitialDuration: {
          type: ['integer'],
        },
        actualMin: {
          type: ['integer'],
        },
        actualOfPlan: {
          type: ['number'],
        },
        actualVisible: {
          type: ['boolean'],
        },
        appHeaderMaxHeight: {
          type: ['integer'],
        },
        arrowHeadOfSpan: {
          type: ['number'],
        },
        arrowHeadOfStroke: {
          type: ['number'],
        },
        assigneeVisible: {
          type: ['boolean'],
        },
        basePlanHeight: {
          type: ['integer'],
        },
        baselineVisible: {
          type: ['boolean'],
        },
        canvasPadding: {
          type: ['integer'],
        },
        carryMaxDepth: {
          type: ['integer'],
        },
        chevronNotchOfHeight: {
          type: ['number'],
        },
        chevronNotchOfWidth: {
          type: ['number'],
        },
        commentBoxPad: {
          type: ['integer'],
        },
        commentBoxWrapUnits: {
          type: ['integer'],
        },
        dateGridLinesVisible: {
          type: ['boolean'],
        },
        dependencyArrowLength: {
          type: ['integer'],
        },
        dependencyLagDefault: {
          type: ['integer'],
        },
        dependencyRunOfArrow: {
          type: ['integer'],
        },
        dependencyVisible: {
          type: ['boolean'],
        },
        dependencyWidth: {
          type: ['number'],
        },
        dualCursor: {
          type: ['object', 'null'],
          properties: {
            date1: {
              type: ['string'],
            },
            date2: {
              type: ['string'],
            },
          },
        },
        dummyOpacity: {
          type: ['number'],
        },
        exportCanvas: {
          type: ['object'],
          properties: {
            width: {
              type: ['integer'],
            },
            height: {
              type: ['integer'],
            },
          },
        },
        exportCanvasHeightCap: {
          type: ['number'],
        },
        fadeHandleHalfPx: {
          type: ['number'],
        },
        fadeHandleStrokePx: {
          type: ['number'],
        },
        fontMin: {
          type: ['integer'],
        },
        fontOfActual: {
          type: ['number'],
        },
        fontScale: {
          enum: ['S', 'M', 'L'],
        },
        fontScaleSizes: {
          type: ['object'],
          properties: {
            L: {
              type: ['integer'],
            },
            M: {
              type: ['integer'],
            },
            S: {
              type: ['integer'],
            },
          },
        },
        groupGridLinesVisible: {
          type: ['boolean'],
        },
        groupLevelOfDetailBase: {
          type: ['number'],
        },
        groupLevelOfDetailRatio: {
          type: ['number'],
        },
        guideCursorMode: {
          enum: ['none', 'crosshair', 'single-vertical'],
        },
        iconHintDelayMs: {
          type: ['integer'],
        },
        importMaxBytes: {
          type: ['integer'],
        },
        importMaxDate: {
          type: ['string'],
        },
        importMaxDepth: {
          type: ['integer'],
        },
        importMaxItems: {
          type: ['integer'],
        },
        importMinDate: {
          type: ['string'],
        },
        labelBaseline: {
          type: ['number'],
        },
        labelCoef: {
          type: ['number'],
        },
        labelGap: {
          type: ['integer'],
        },
        labelHaloOfFont: {
          type: ['number'],
        },
        labelPad: {
          type: ['integer'],
        },
        markerGap: {
          type: ['integer'],
        },
        markerSize: {
          type: ['integer'],
        },
        markerStroke: {
          type: ['number'],
        },
        maxGroupDepth: {
          type: ['integer'],
        },
        milestoneActualDuration: {
          type: ['integer'],
        },
        minShapeWidth: {
          type: ['integer'],
        },
        percentCompleteVisible: {
          type: ['boolean'],
        },
        pinnedGroupIds: {
          type: ['array'],
          items: {
            type: ['string'],
          },
        },
        pinnedRowMax: {
          type: ['integer'],
        },
        planActualGuidePattern: {
          type: ['object'],
          properties: {
            off: {
              type: ['number'],
            },
            on: {
              type: ['number'],
            },
          },
        },
        planActualGuideWeight: {
          type: ['number'],
        },
        planStroke: {
          type: ['integer'],
        },
        planVisible: {
          type: ['boolean'],
        },
        progressLineOverhang: {
          type: ['integer'],
        },
        progressLineVisible: {
          type: ['boolean'],
        },
        progressLineWidth: {
          type: ['number'],
        },
        progressMarkerVisible: {
          type: ['boolean'],
        },
        propertyPanelWidth: {
          type: ['number'],
        },
        pxPerDayAt1x: {
          type: ['number'],
        },
        resumeArmOfMarker: {
          type: ['number'],
        },
        resumeDashOff: {
          type: ['integer'],
        },
        resumeDashOn: {
          type: ['integer'],
        },
        resumeHeadOfMarker: {
          type: ['number'],
        },
        resumeScaleInvalid: {
          type: ['number'],
        },
        rowGap: {
          type: ['integer'],
        },
        rowTitleFont: {
          type: ['integer'],
        },
        rowTitleIndent: {
          type: ['integer'],
        },
        rowTitlePanelWidth: {
          type: ['number'],
        },
        rowTitleTopScale: {
          type: ['number'],
        },
        rulerFont: {
          type: ['number'],
        },
        rulerHeight: {
          type: ['number'],
        },
        rulerLabelBottomPad: {
          type: ['integer'],
        },
        rulerLabelGap: {
          type: ['integer'],
        },
        rulerLabelPad: {
          type: ['integer'],
        },
        rulerTierPxPerDayDay: {
          type: ['number'],
        },
        rulerTierPxPerDayMonth: {
          type: ['number'],
        },
        rulerTierPxPerDayWeek: {
          type: ['number'],
        },
        scrollDate: {
          type: ['string', 'null'],
        },
        scrollDayOffset: {
          type: ['number'],
        },
        scrollGroupId: {
          type: ['string', 'null'],
        },
        scrollGroupOffset: {
          type: ['number'],
        },
        shapeHeightOf: {
          type: ['object'],
          properties: {
            arrow: {
              type: ['number'],
            },
            chevron: {
              type: ['number'],
            },
            endpointSpan: {
              type: ['number'],
            },
            milestone: {
              type: ['number'],
            },
            rectangle: {
              type: ['number'],
            },
          },
        },
        spanDotOfStroke: {
          type: ['number'],
        },
        stackDirection: {
          enum: ['up', 'down'],
        },
        stackGap: {
          type: ['integer'],
        },
        stackSafetyCap: {
          type: ['integer'],
        },
        starInnerOfOuter: {
          type: ['number'],
        },
        taskLevelOfDetailReadablePx: {
          type: ['integer'],
        },
        themeMonochrome: {
          type: ['boolean'],
        },
        themePreference: {
          enum: ['light', 'dark'],
        },
        thinFontScale: {
          type: ['number'],
        },
        thinStrokeMax: {
          type: ['integer'],
        },
        thinStrokeMin: {
          type: ['number'],
        },
        thinStrokeOfPlan: {
          type: ['number'],
        },
        truncateUnits: {
          type: ['integer'],
        },
        zoomX: {
          type: ['number'],
        },
        zoomY: {
          type: ['number'],
        },
      },
    },
    documentStamp: {
      ref: 'documentStamp',
    },
    changeLog: {
      type: ['array'],
      items: {
        ref: 'changeLog',
      },
    },
  },
}

// </generated>

/** Named once because `documentFromJson` must tell this finding apart (FR-073). */
const NOT_A_KEY_THIS_SHAPE_CARRIES = 'is not a key this shape carries'

/** @purity pure */
function fault(at: string, what: string): JsonFault {
  return { at, what }
}

/**
 * Whether a fault is only that this build does not know the key.
 *
 * @purity pure
 */
function isUnknownKeyFault(one: JsonFault): boolean {
  return one.what === NOT_A_KEY_THIS_SHAPE_CARRIES
}

/**
 * The column a fault about an unknown key names -- the last step of its JSON
 * pointer, with RFC 6901's two escapes undone.
 *
 * @purity pure
 */
function columnOf(at: string): string {
  const last = at.slice(at.lastIndexOf('/') + 1)
  return last.replace(/~1/g, '/').replace(/~0/g, '~')
}

/** @purity pure */
function refusal(faults: readonly JsonFault[]): JsonDecoding {
  return { ok: false, reason: 'RS-25', faults }
}

/** @purity pure */
function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

/**
 * One step down a JSON pointer (RFC 6901). The escapes matter: the `carry` maps
 * take any key the exchange partner wrote, and an unescaped `/` would point at
 * the wrong place.
 *
 * @purity pure
 */
function pointer(at: string, key: string): string {
  return `${at}/${key.replace(/~/g, '~0').replace(/\//g, '~1')}`
}

/**
 * Whether a value is of one of the schema's kinds. The `never` floor makes a
 * kind the manuscript grows a compile error here rather than a skipped rule.
 *
 * @purity pure
 */
function jsonTypeHolds(value: unknown, kind: JsonSchemaKind): boolean {
  switch (kind) {
    case 'null':
      return value === null
    case 'boolean':
      return typeof value === 'boolean'
    case 'integer':
      // ⚠️ JSON has one number type; "integer" is a condition on the value.
      return typeof value === 'number' && Number.isInteger(value)
    case 'number':
      return typeof value === 'number' && Number.isFinite(value)
    case 'string':
      return typeof value === 'string'
    case 'array':
      return Array.isArray(value)
    case 'object':
      return isObject(value)
    default: {
      const unreached: never = kind
      return unreached
    }
  }
}

/**
 * What a value is, in the words a fault says it in (NT-1: 文字で示すこと).
 *
 * @purity pure
 */
function jsonTypeOf(value: unknown): string {
  if (value === null) return 'null'
  if (Array.isArray(value)) return 'an array'
  if (typeof value === 'number') return Number.isInteger(value) ? 'an integer' : 'a number'
  if (typeof value === 'string') return 'a string'
  if (typeof value === 'boolean') return 'a boolean'
  if (isObject(value)) return 'an object'
  return typeof value
}

/**
 * Walks one value against one node of the generated schema, collecting every
 * fault rather than stopping at the first (NT-1).
 *
 * `CarryElement` refers to itself, so on `carryElements` the recursion depth
 * follows the data.
 *
 * @purity pure
 */
function collectFaults(
  value: unknown,
  node: SchemaNode,
  at: string,
  out: JsonFault[],
): void {
  if (node.ref !== undefined) {
    const target = SCHEMA_DEFS[node.ref]
    if (target !== undefined) collectFaults(value, target, at, out)
    return
  }

  const kinds = node.type
  if (kinds !== undefined && !kinds.some((kind) => jsonTypeHolds(value, kind))) {
    // Stops here: the children would each report again on the one wrong type.
    out.push(fault(at, `expected ${kinds.join(' or ')}, was ${jsonTypeOf(value)}`))
    return
  }

  const members = node.enum
  if (members !== undefined && !(members as readonly unknown[]).includes(value)) {
    out.push(
      fault(at, `is not one of ${members.map((one) => JSON.stringify(one)).join(', ')}`),
    )
    return
  }

  if (typeof value === 'number') {
    if (node.minimum !== undefined && value < node.minimum) {
      out.push(fault(at, `is below the least value allowed, ${node.minimum}`))
    }
    if (node.maximum !== undefined && value > node.maximum) {
      out.push(fault(at, `is above the greatest value allowed, ${node.maximum}`))
    }
  }
  if (
    typeof value === 'string' &&
    node.maxLength !== undefined &&
    value.length > node.maxLength
  ) {
    out.push(fault(at, `is longer than the ${node.maxLength} characters allowed`))
  }

  if (isObject(value)) {
    for (const key of node.required ?? []) {
      if (!(key in value)) out.push(fault(pointer(at, key), 'is missing'))
    }
    for (const [key, inner] of Object.entries(value)) {
      const child = node.properties?.[key] ?? node.values
      if (child !== undefined) {
        collectFaults(inner, child, pointer(at, key), out)
      } else if (node.closed === true) {
        out.push(fault(pointer(at, key), NOT_A_KEY_THIS_SHAPE_CARRIES))
      }
    }
  }

  const items = node.items
  if (items !== undefined && Array.isArray(value)) {
    value.forEach((element, index) => collectFaults(element, items, `${at}/${index}`, out))
  }
}

/**
 * FR-073's comparison: `>` on the strings, not a parsed date. Equal and older
 * are one answer, because FR-073 treats only strictly newer as unreadable.
 *
 * @purity pure
 */
function formatVersionReading(
  schemaVersion: string,
  greatestKnownSchemaVersion: string | undefined,
): FormatVersionReading {
  if (greatestKnownSchemaVersion === undefined) return 'notCompared'
  return schemaVersion > greatestKnownSchemaVersion ? 'newerThanKnown' : 'known'
}

/**
 * Reads one `GRS JSON` text.
 *
 * It takes the text rather than a parsed value, because parsing is where a
 * malformed input announces itself.
 *
 * The BOM is dropped before `JSON.parse`, which would otherwise refuse the file
 * for the one reason FR-023 forbids. The drop is `mspdi-codec.ts`'s helper, so
 * the two intake paths cannot disagree.
 *
 * The shape is judged by the generated schema alone, so no value the manuscript
 * holds is copied here.
 *
 * `greatestKnownSchemaVersion` arrives as an argument: it is the version the
 * generator wrote into the bundled template, and holding it here would be a
 * second copy of a generated value. Leaving it out yields `notCompared`.
 *
 * @purity pure
 */
export function documentFromJson(
  text: string,
  greatestKnownSchemaVersion?: string,
): JsonDecoding {
  let parsed: unknown
  try {
    parsed = JSON.parse(withoutLeadingByteOrderMark(text))
  } catch (why) {
    return refusal([
      fault('', `not JSON: ${why instanceof Error ? why.message : String(why)}`),
    ])
  }

  // Judged before the faults are weighed, because a newer document must still
  // open (FR-073). Read off the parsed value, since `read` is only assumed to be
  // a document afterwards; a missing `schemaVersion` reads as `''`, never newer.
  const declared = isObject(parsed) ? parsed['schemaVersion'] : undefined
  const formatVersion = formatVersionReading(
    typeof declared === 'string' ? declared : '',
    greatestKnownSchemaVersion,
  )

  const faults: JsonFault[] = []
  collectFaults(parsed, GRS_DOCUMENT_SCHEMA, '', faults)
  // In a newer document only an unknown key is forgiven, as FR-073's finding;
  // every other fault still refuses. In a known version it stays RS-25's.
  const isNewer = formatVersion === 'newerThanKnown'
  const refusing = isNewer ? faults.filter((one) => !isUnknownKeyFault(one)) : faults
  if (refusing.length > 0) return refusal(refusing)
  const unreadColumns = isNewer
    ? [...new Set(faults.filter(isUnknownKeyFault).map((one) => columnOf(one.at)))]
    : []

  // The assertion over-claims: `Document` gives the presentation group every
  // key, but filling a missing setting is ImportDocument's (OP-6), and table
  // T-220's preamble forbids refusing one here.
  const read = parsed as unknown as Document

  // `clampedSettings` (PI-2) runs on the read road rather than in each caller, so
  // every road that turns `GRS JSON` into a document gets it once.

  const clamp = clampedSettings(read.documentSettings)
  if (clamp.clamped.length === 0) {
    return { ok: true, document: read, clampedCount: 0, formatVersion, unreadColumns }
  }
  // A new root: `clampedSettings` returns a fresh group, unknown keys included.
  return {
    ok: true,
    document: { ...read, documentSettings: clamp.settings },
    clampedCount: clamp.clamped.length,
    formatVersion,
    unreadColumns,
  }
}

/**
 * Writes one `GRS JSON` text.
 *
 * Every settings key and every `null` column is written (FR-024), which
 * `JSON.stringify` already does because the document type has no optional key.
 * Do not drop defaults: a later default change must not move the picture of a
 * document written today.
 *
 * @purity pure
 */
export function jsonFromDocument(document: Document): string {
  return JSON.stringify(document, null, 1) + '\n'
}
