# -*- coding: utf-8 -*-
"""Write the GRS JSON schema into the reading path as a runnable validator.

Chapter 6.1 of docs/spec/05-07-design.md (the preamble of table T-220) excuses
its own table from every condition a single column decides, on the stated
ground that `_source/grs-document.schema.json` already enforces those. Until
this generator existed that ground was false in the product: the schema was an
artifact three comments pointed at and nothing ever ran.

The same preamble now says the schema MUST actually run on the road that reads
`GRS JSON`, and names the place -- the side that assembles the document,
`CP-20` of table T-062, which is src/adapter/document-codec. So the schema is
turned into TypeScript and planted inside that unit:

  src/adapter/document-codec/json-codec.ts    the node table the walker reads

⛔ ajv is NOT bundled, by the user's ruling of 2026-08-24. `PO-4` of table
T-232 allows script-src exactly one sha256, and ajv's ordinary compile builds
its validator with `new Function`, which that one hash cannot cover in the
single file://-openable page; ajv's standalone output grows the artifact by
28-34%. ⭐ The measurement that makes a hand-rolled walker safe: the generated
schema speaks only ten keywords (EXPRESSED below), and this generator REFUSES
to run when it grows an eleventh, so the walker can never be handed a rule it
would silently ignore.

Two departures from the manuscript, both required rather than chosen:

⛔ The `documentSettings` group loses `required` and `additionalProperties:
false`, through its whole subtree. The preamble forbids applying either to that
group (MUST NOT) because `OP-6` of table T-024a orders the reading side to fill
a missing setting with its default and to KEEP an unknown key; a schema that
refused those would have one half of the build reject what the other half
accepts.

⛔ The same group also loses every bound -- `minimum`, `maximum`, `maxLength`.
The preamble of table T-220 was corrected on 2026-08-24: it now names `type`
and `enum` as the ONLY conditions that group may carry (MUST), and forbids
refusing a value for being out of bounds (MUST NOT), because that job belongs
to `clampedSettings` of `PI-2` (table T-064), which moves an out-of-bounds
value into range instead of rejecting it. ⚠️ The earlier wording said "type,
range and enumeration", and this generator was faithful to it; the wording was
the error, so the reduction moved rather than the manuscript. ⭐ What survives
there is now exactly the type and the enumeration of each key.

⛔ `format` is dropped, by the user's ruling. Its 15 uses are 2 dates, 3
datetimes and 10 uuids. The dates and datetimes are already held as a condition
by `IV-14` of table T-220, so honouring `format` here would be the second key
for one thing. ⛔ THE 10 uuid COLUMNS ARE THEREFORE CHECKED BY NOBODY -- see
the list this tool prints, and PD-189, which has not been ruled on.

Only what sits between the two markers belongs to this generator; everything a
person writes around it is left alone, exactly as tools/generate_entity_types.py
does.

  python tools/generate_json_schema_validator.py            write the region
  python tools/generate_json_schema_validator.py --check    fail on drift

Run with PYTHONIOENCODING=utf-8.
"""
import collections
import io
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SCHEMA = os.path.join(ROOT, 'docs', 'spec', '_source', 'grs-document.schema.json')
TARGET = os.path.join(ROOT, 'src', 'adapter', 'document-codec', 'json-codec.ts')

# ⚠️ The marker carries NO path, for the reason generate_entity_types.py
# records: a marker that names the manuscript stops matching when the
# manuscript moves, and the region is then APPENDED rather than replaced.
OPEN = '// <generated -- do not edit by hand>'
CLOSE = '// </generated>'

SOURCES = [
    'docs/spec/_source/grs-document.schema.json',
    '  (itself generated by docs/spec/_source/erd_json_to_schema.py from',
    '   erd.json and docs/spec/_assets/tbl-settings.md)',
]

# The ten keywords this generator turns into something the walker obeys.
EXPRESSED = frozenset((
    'type', 'required', 'properties', '$ref', 'items',
    'additionalProperties', 'enum', 'minimum', 'maximum', 'maxLength',
))

# ⭐ Carried nowhere, on purpose, one reason each. A keyword that is neither
# expressed nor listed here stops this generator -- which is the whole safety
# of not using a real JSON Schema engine.
DROPPED = {
    '$schema': 'names the dialect; the walker implements one dialect only',
    '$id': 'the manuscript\'s own address, of no use to a reader of values',
    'title': 'prose',
    'description': 'prose',
    '$comment': 'prose',
    'default': 'a validator judges what is there; it does not fill in',
    'format': 'the user\'s ruling of 2026-08-24 -- see the head of this file',
}

# The path under which the strictness keywords must not be applied.
# ⛔ Stated as the pointer rather than as the word, so that a rename of the
# group in the manuscript stops this generator instead of quietly re-arming
# the very conditions the preamble of table T-220 forbids.
RELAXED_ROOT = '/documentSettings'

# ⛔ Everything the relaxed group must NOT carry, by the name the walker reads
# it under. `required` and `closed` are here for `OP-6` of table T-024a; the
# three bounds are here because the preamble of table T-220 leaves the range to
# `clampedSettings` (`PI-2` of table T-064) -- see the head of this file.
# ⭐ Listed rather than written out at each site, so that "only the type and
# the enumeration survive there" is one line a reader can check.
RELAXED_OFF = frozenset(('required', 'closed', 'minimum', 'maximum',
                         'maxLength'))

say = lambda m: sys.stdout.write(m + '\n')


def ordered(path):
    return json.load(io.open(path, encoding='utf-8'),
                     object_pairs_hook=collections.OrderedDict)


def unknown_keyword(keyword, at):
    raise SystemExit(
        'generate_json_schema_validator: the schema uses %r at %r, which this\n'
        '  generator neither expresses nor deliberately drops.\n'
        '  ⛔ Do not ignore it: a rule nobody runs is the state the preamble of\n'
        '  table T-220 was written to end. Teach the walker in json-codec.ts to\n'
        '  obey it and add it to EXPRESSED, or add it to DROPPED with the reason.'
        % (keyword, at or '/'))


def reduce_node(node, at, formats):
    """One schema node, cut down to what the walker in json-codec.ts obeys."""
    if not isinstance(node, dict):
        raise SystemExit('generate_json_schema_validator: %r is not a schema '
                         'node' % (at,))
    out = collections.OrderedDict()
    for keyword in node:
        if keyword in DROPPED:
            if keyword == 'format':
                formats.append((at, node[keyword]))
            continue
        if keyword not in EXPRESSED:
            unknown_keyword(keyword, at)

    if '$ref' in node:
        # ⛔ A reference with siblings would mean the siblings apply ON TOP of
        # the target, which the walker does not do. The manuscript never writes
        # one; stop rather than drop them.
        siblings = [k for k in node if k != '$ref' and k not in DROPPED]
        if siblings:
            raise SystemExit(
                'generate_json_schema_validator: %r puts %s beside "$ref". The '
                'walker resolves a reference and stops.' % (at, siblings))
        target = node['$ref']
        if not target.startswith('#/$defs/'):
            raise SystemExit('generate_json_schema_validator: %r references '
                             '%r, which is not a local definition' % (at, target))
        out['ref'] = target[len('#/$defs/'):]
        return out

    if 'type' in node:
        kinds = node['type']
        out['type'] = [kinds] if isinstance(kinds, str) else list(kinds)
    if 'enum' in node:
        out['enum'] = list(node['enum'])

    strict = not (at == RELAXED_ROOT or at.startswith(RELAXED_ROOT + '/'))
    keeps = (lambda keyword: strict or keyword not in RELAXED_OFF)

    for keyword in ('minimum', 'maximum', 'maxLength'):
        if keyword in node and keeps(keyword):
            out[keyword] = node[keyword]
    if 'required' in node and keeps('required'):
        out['required'] = list(node['required'])
    if 'additionalProperties' in node:
        extra = node['additionalProperties']
        if extra is False:
            if keeps('closed'):
                out['closed'] = True
        elif isinstance(extra, dict):
            # A map whose keys are free and whose values have one shape --
            # `carry` is the only one the manuscript writes.
            out['values'] = reduce_node(extra, at + '/{}', formats)
        else:
            raise SystemExit('generate_json_schema_validator: %r gives '
                             '"additionalProperties" the value %r' % (at, extra))
    if 'properties' in node:
        properties = collections.OrderedDict()
        for key, inner in node['properties'].items():
            properties[key] = reduce_node(inner, at + '/' + key, formats)
        out['properties'] = properties
    if 'items' in node:
        out['items'] = reduce_node(node['items'], at + '/[]', formats)
    return out


IDENTIFIER = re.compile(r'[A-Za-z_$][A-Za-z0-9_$]*\Z')


def ts_key(key):
    return key if IDENTIFIER.match(key) else ts_string(key)


def ts_string(text):
    # The manuscript's keys and enum members are plain ASCII words; escaping is
    # here so that one day they may stop being so without this going wrong.
    return "'%s'" % text.replace('\\', '\\\\').replace("'", "\\'")


def ts_scalar(value):
    if value is None:
        return 'null'
    if isinstance(value, bool):
        return 'true' if value else 'false'
    if isinstance(value, str):
        return ts_string(value)
    return repr(value)


def ts_node(node, indent):
    """One reduced node as a TypeScript object literal."""
    pad = '  ' * indent
    inner = '  ' * (indent + 1)
    lines = ['{']
    for keyword, value in node.items():
        if keyword in ('ref',):
            lines.append('%s%s: %s,' % (inner, keyword, ts_string(value)))
        elif keyword == 'type':
            lines.append('%stype: [%s],'
                         % (inner, ', '.join(ts_string(t) for t in value)))
        elif keyword == 'enum':
            lines.append('%senum: [%s],'
                         % (inner, ', '.join(ts_scalar(v) for v in value)))
        elif keyword == 'required':
            lines.append('%srequired: [%s],'
                         % (inner, ', '.join(ts_string(k) for k in value)))
        elif keyword == 'closed':
            lines.append('%sclosed: true,' % inner)
        elif keyword in ('minimum', 'maximum', 'maxLength'):
            lines.append('%s%s: %s,' % (inner, keyword, ts_scalar(value)))
        elif keyword in ('values', 'items'):
            lines.append('%s%s: %s,' % (inner, keyword, ts_node(value, indent + 1)))
        elif keyword == 'properties':
            lines.append('%sproperties: {' % inner)
            for key, child in value.items():
                lines.append('%s  %s: %s,'
                             % (inner, ts_key(key), ts_node(child, indent + 2)))
            lines.append('%s},' % inner)
        else:
            raise SystemExit('generate_json_schema_validator: nothing emits %r'
                             % keyword)
    lines.append('%s}' % pad)
    return '\n'.join(lines)


# ⚠️ An enum MEMBER is a value, not a type, and the manuscript writes `null`
# as one -- `nameAlign` and the four other unspelled enumerations of table
# T-058 admit it. Measured rather than assumed, for the reason KIND_ORDER is.
TS_OF_MEMBER = {
    type(None): 'null',
    bool: 'boolean',
    int: 'number',
    float: 'number',
    str: 'string',
}
MEMBER_ORDER = ('null', 'boolean', 'number', 'string')


def members_used(node, found):
    for member in node.get('enum', ()):
        kind = TS_OF_MEMBER.get(type(member))
        if kind is None:
            raise SystemExit('generate_json_schema_validator: an enum member '
                             'is %r, which TS_OF_MEMBER does not map' % (member,))
        found.add(kind)
    for child in node.get('properties', {}).values():
        members_used(child, found)
    for keyword in ('items', 'values'):
        if keyword in node:
            members_used(node[keyword], found)
    return found


def kinds_used(node, found):
    for kind in node.get('type', ()):
        found.add(kind)
    for child in node.get('properties', {}).values():
        kinds_used(child, found)
    for keyword in ('items', 'values'):
        if keyword in node:
            kinds_used(node[keyword], found)
    return found


# ⭐ The order a reader wants, not the order a set gives.
KIND_ORDER = ('null', 'boolean', 'integer', 'number', 'string', 'array', 'object')

HEAD = [
    '/**',
    ' * The schema of `GRS JSON`, as the walker below reads it.',
    ' *',
    ' * ⭐ ONE NODE PER SCHEMA NODE. `ref` names a member of SCHEMA_DEFS and',
    ' * stands alone; `closed` is `additionalProperties: false`; `values` is',
    ' * `additionalProperties` given a shape (the `carry` maps).',
    ' */',
]


def build(schema):
    formats = []
    defs = collections.OrderedDict()
    for name, node in schema.get('$defs', {}).items():
        defs[name] = reduce_node(node, '/$defs/' + name, formats)
    root_source = collections.OrderedDict(
        (k, v) for k, v in schema.items() if k != '$defs')
    root = reduce_node(root_source, '', formats)
    # ⚠️ The root's own properties are reached through the pointer the
    # relaxation is stated with, so `documentSettings` is already relaxed by
    # reduce_node; nothing re-opens it here.

    found = set()
    for node in defs.values():
        kinds_used(node, found)
    kinds_used(root, found)
    seen_members = set()
    for node in defs.values():
        members_used(node, seen_members)
    members_used(root, seen_members)
    members = [m for m in MEMBER_ORDER if m in seen_members] or ['never']
    unordered = sorted(found - set(KIND_ORDER))
    if unordered:
        raise SystemExit('generate_json_schema_validator: the schema uses the '
                         'type(s) %s, which KIND_ORDER does not list' % unordered)
    kinds = [k for k in KIND_ORDER if k in found]

    lines = []
    lines.append('/**')
    lines.append(' * Every `type` the manuscript actually writes.')
    lines.append(' *')
    lines.append(' * ⭐ Measured, not enumerated: `jsonTypeHolds` below switches over this')
    lines.append(' * union with a `never` floor, so a type the manuscript grows is a compile')
    lines.append(' * error in the walker rather than a rule that is quietly skipped.')
    lines.append(' */')
    lines.append('type JsonSchemaKind =')
    for kind in kinds:
        lines.append('  | %s' % ts_string(kind))
    lines.append('')
    lines.extend(HEAD)
    lines.append('interface SchemaNode {')
    lines.append('  readonly ref?: string')
    lines.append('  readonly type?: readonly JsonSchemaKind[]')
    lines.append('  readonly enum?: readonly (%s)[]' % ' | '.join(members))
    lines.append('  readonly minimum?: number')
    lines.append('  readonly maximum?: number')
    lines.append('  readonly maxLength?: number')
    lines.append('  readonly required?: readonly string[]')
    lines.append('  readonly closed?: true')
    lines.append('  readonly values?: SchemaNode')
    lines.append('  readonly properties?: Readonly<Record<string, SchemaNode>>')
    lines.append('  readonly items?: SchemaNode')
    lines.append('}')
    lines.append('')
    lines.append('/** The `$defs` of the manuscript, by the name a `ref` gives. */')
    lines.append('const SCHEMA_DEFS: Readonly<Record<string, SchemaNode>> = {')
    for name, node in defs.items():
        lines.append('  %s: %s,' % (ts_key(name), ts_node(node, 1)))
    lines.append('}')
    lines.append('')
    lines.append('/**')
    lines.append(' * The document root.')
    lines.append(' *')
    lines.append(' * ⛔ `documentSettings` carries neither `required` nor `closed`, here or')
    lines.append(' * anywhere below it: the preamble of table T-220 forbids both on that')
    lines.append(' * group (MUST NOT) because `OP-6` of table T-024a has the reader fill a')
    lines.append(' * missing setting with its default and KEEP a key it does not know.')
    lines.append(' *')
    lines.append(' * ⛔ It carries no bound either -- no `minimum`, `maximum` or `maxLength`.')
    lines.append(' * The same preamble allows that group the type and the enumeration only')
    lines.append(' * (MUST) and forbids refusing a value for being out of bounds (MUST NOT),')
    lines.append(' * because the range is the work of `clampedSettings` (`PI-2` of table')
    lines.append(' * T-064), which moves such a value into range rather than rejecting it.')
    lines.append(' * ⚠️ Refusing here would shut a whole document out over one display key.')
    lines.append(' *')
    lines.append(' * ⛔ AND NOBODY CALLS `clampedSettings` YET. It is exported from')
    lines.append(' * entity/document-model/document-settings, and outside its own unit tests')
    lines.append(' * the call sites in src/ number ZERO -- so an out-of-bounds setting is')
    lines.append(' * now neither refused here nor clamped anywhere. ⚠️ The manuscript does')
    lines.append(' * not say on which road the call belongs, so the wiring is deliberately')
    lines.append(' * NOT guessed at here; it needs a ruling before it can be written.')
    lines.append(' */')
    lines.append('const GRS_DOCUMENT_SCHEMA: SchemaNode = %s' % ts_node(root, 0))
    return '\n'.join(lines) + '\n', formats


def provenance(sources):
    out = ['// Single source of truth:']
    out.extend('//   %s' % s for s in sources)
    out.append('// Rebuild: npm run gen   ||   npm run gen:check fails on drift.')
    return '\n'.join(out) + '\n'


def region(text, body):
    """Replace the marked region, leaving everything around it untouched."""
    block = '%s\n%s\n%s\n' % (OPEN, body, CLOSE)
    if OPEN in text:
        head, rest = text.split(OPEN, 1)
        _old, tail = rest.split(CLOSE, 1)
        tail = tail.lstrip('\n')
        return head + block + ('\n' + tail if tail else '')
    raise SystemExit(
        'generate_json_schema_validator: %s has no generated region.\n'
        '  Put these two lines where the node table belongs, then run again:\n'
        '    %s\n    %s'
        % (os.path.relpath(TARGET, ROOT).replace('\\', '/'), OPEN, CLOSE))


def main():
    schema = ordered(SCHEMA)
    body, formats = build(schema)
    checking = '--check' in sys.argv

    unchecked = [at for at, kind in formats if kind == 'uuid']
    if unchecked and not checking:
        # ⛔ Printed every run rather than buried: these columns are now the only
        # ones in the document that NOBODY judges.
        # ⚠️ ASCII on purpose: a Windows console runs cp932 and the marks this
        # file uses in its prose cannot be encoded there, which killed the run
        # rather than printing the warning.
        say('UNCHECKED  %d column(s) carry "format": "uuid". Nothing judges '
            'them; PD-189 is unruled:' % len(unchecked))
        for at in unchecked:
            say('     %s' % at)

    current = io.open(TARGET, encoding='utf-8', newline='').read()
    wanted = region(current, provenance(SOURCES) + body)
    rel = os.path.relpath(TARGET, ROOT).replace('\\', '/')
    if checking:
        if current != wanted:
            say('DRIFTED  %s no longer matches grs-document.schema.json -- '
                'rerun generate_json_schema_validator.py' % rel)
            return 1
        say('OK       the generated validator still matches the schema')
        return 0
    io.open(TARGET, 'w', encoding='utf-8', newline='\n').write(wanted)
    say('wrote %s' % rel)
    return 0


if __name__ == '__main__':
    sys.exit(main())
