# -*- coding: utf-8 -*-
"""Print the image-to-GRS-JSON prompt the app copies (FR-068) into src/.

    python tools/generate_image_to_grs_json_prompt.py
    python tools/generate_image_to_grs_json_prompt.py --check

FR-068 (MUST) has the header entrance IC-115 copy ONE string to the clipboard:
the prompt manuscript in the display language, a version line, the GRS JSON
schema and the base document, in that order. Section 6.2 of 05-07-design.md
keeps the manuscripts in docs/spec/_source/ (one per language) and forbids
(MUST NOT) copying the schema or the base document into them: this generator
appends both. The shell joins the pieces at the press (CR-562 section 5):

    <prompt[lang]> "\\n\\n" "schemaVersion: " <schemaVersion>
    "\\n\\n```json\\n" <schema> "\\n```\\n\\n```json\\n" <emptyDocument> "\\n```\\n"

THE JOINED STRING IS NOT STORED. Each language would carry the schema and the
base document a second time (CR-562 section 5), so the artifact holds the parts
and the join is the shell's one line.

THE PIECES ARE READ, NEVER RETYPED.
  prompt         docs/spec/_source/image-to-grs-json-prompt.<lang>.md, from its
                 second line (the first line declares the file's role and is
                 not part of the prompt -- 05-07-design.md 6.2)
  schemaVersion  the startup template's version (FR-027), taken from
                 tools/generate_startup_template.py, which prints that template
  schema         docs/spec/_source/grs-document.schema.json, whitespace removed
  emptyDocument  a GRS JSON with no task, built from the same pieces the
                 startup template is built from (version, documentSettings,
                 calendar, project defaults) and refused unless the startup
                 generator's own schema check passes it (FR-068, DFC-921)

Run with PYTHONIOENCODING=utf-8.
"""
import io
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

import generate_startup_template as startup  # noqa: E402

SOURCE = os.path.join(ROOT, 'docs', 'spec', '_source')
MANUSCRIPT_NAME = 'image-to-grs-json-prompt.%s.md'
LANGUAGES = ('ja', 'en')
SCHEMA = os.path.join(SOURCE, 'grs-document.schema.json')
OUT = os.path.join(ROOT, 'src', 'adapter', 'screen-renderer',
                   'image-to-grs-json-prompt.json')
REL_OUT = 'src/adapter/screen-renderer/image-to-grs-json-prompt.json'
REL_SELF = 'tools/generate_image_to_grs_json_prompt.py'

# The role declaration check 21 looks for on the manuscript's first line.
ROLE_MARK = 'SINGLE SOURCE OF TRUTH'
# What the manuscript must not hold (05-07-design.md 6.2, MUST NOT): a fenced
# block would be a copy of the schema or the base document.
FENCE = '```'

# The base document's stamp. The author is the word the prompt manuscripts
# tell the AI it may leave in place ("ai-conversion"); the instants are the
# startup template's, and the file has never been saved (AT-140).
BASE_AUTHOR = 'ai-conversion'
# The one row the base document carries: the prompt asks for at least one
# TaskGroup, and the base is what the AI copies whole.
BASE_ROW = {
    'id': '00000000-0000-4000-8000-000000000001',
    'label': 'Row 1',
}
# Project columns that describe the startup template's fictional plan. The
# base document is a blank the AI fills, so each is null there.
BLANKED_PROJECT_COLUMNS = (
    'name', 'title', 'subject', 'category', 'company', 'manager', 'author',
    'created', 'revision', 'lastSaved', 'startDate', 'statusDate',
)

BANNER = (
    'GENERATED by %s -- do not edit by hand. Rebuild: npm run gen  |  '
    'npm run gen:check fails on drift. Generated from '
    'docs/spec/_source/image-to-grs-json-prompt.ja.md, '
    'docs/spec/_source/image-to-grs-json-prompt.en.md (each from its second '
    'line), docs/spec/_source/grs-document.schema.json (minified) and '
    'tools/generate_startup_template.py (schemaVersion, and the pieces of the '
    'base document). FR-068: the copied string is prompt[lang] + blank line + '
    '"schemaVersion: " + schemaVersion + blank line + a json fence holding '
    'schema + blank line + a json fence holding emptyDocument; the join is '
    'not stored (CR-562 section 5).' % REL_SELF
)


def say(message):
    """The cp932 guard every generator in this tree carries."""
    enc = getattr(sys.stdout, 'encoding', None) or 'utf-8'
    sys.stdout.write(message.encode(enc, 'replace').decode(enc) + '\n')


def prompt_of(language):
    """One manuscript from its second line, with LF line ends.

    @purity semi-pure-b
    """
    name = MANUSCRIPT_NAME % language
    text = io.open(os.path.join(SOURCE, name), encoding='utf-8').read()
    text = text.replace('\r\n', '\n')
    first, _, body = text.partition('\n')
    if ROLE_MARK not in first:
        sys.exit('%s: the first line does not declare the file as the %s, '
                 'so it cannot be told from the prompt (05-07-design.md 6.2)'
                 % (name, ROLE_MARK))
    body = body.strip('\n')
    if not body:
        sys.exit('%s holds no prompt after its first line' % name)
    if FENCE in body:
        sys.exit('%s holds a fenced block; the schema and the base document '
                 'are appended by this generator and must not be copied into '
                 'the manuscript (05-07-design.md 6.2, MUST NOT)' % name)
    return body


def minified(value):
    """One line of JSON with no whitespace between tokens."""
    return json.dumps(value, ensure_ascii=False, separators=(',', ':'))


def empty_project():
    """The startup template's project with the plan's own values blanked.

    @purity semi-pure-b
    """
    built = startup.Builder(startup.settings_defaults())
    project = built.project(0, startup.manuscript_number('S-73'))
    for column in BLANKED_PROJECT_COLUMNS:
        project[column] = None
    project['uidHighWaterMark'] = 0
    return project


def empty_calendar():
    """The startup template's calendar without its shutdowns.

    S-107 keeps the default calendar free of exceptions, since holding them
    would presume a region; the template's shutdowns belong to its own plan.

    @purity semi-pure-b
    """
    calendar = startup.Builder(startup.settings_defaults()).calendar()
    calendar['exceptions'] = []
    return calendar


def empty_document():
    """A GRS JSON with no task, at the startup template's version (FR-068).

    @purity semi-pure-b
    """
    settings = startup.settings_defaults()
    startup.assert_settings_complete(settings)
    document = {
        'schemaVersion': startup.SCHEMA_VERSION,
        'schedule': {
            'project': empty_project(),
            'calendars': [empty_calendar()],
            'tasks': [],
            'resources': [],
            'assignments': [],
            'taskGroups': [{
                'id': BASE_ROW['id'],
                'parentId': None,
                'label': BASE_ROW['label'],
                'derivedFromTaskUid': None,
                'order': 0,
                'treeState': 'auto',
                'editGroup': None,
                'color': None,
                'minHeight': None,
            }],
            'taskGroupMembers': [],
            'taskVisuals': [],
            'commentBoxes': [],
            'highlightBoxes': [],
            'taskOrigins': [],
            'baselineTasks': [],
        },
        'documentSettings': settings,
        'documentStamp': {
            'scheduleUpdatedUtc': startup.STAMPED_AT,
            'lastEditedBy': BASE_AUTHOR,
            'settingsUpdatedUtc': startup.STAMPED_AT,
            'fileSavedUtc': None,
        },
        'changeLog': [],
    }
    startup.check_schema(document)
    return document


def build():
    """The artifact: the parts of the copied string, each once.

    @purity semi-pure-b
    """
    schema = json.load(io.open(SCHEMA, encoding='utf-8'))
    built = {'$comment': BANNER}
    for language in LANGUAGES:
        built[language] = prompt_of(language)
    built['schemaVersion'] = startup.SCHEMA_VERSION
    built['schema'] = minified(schema)
    built['emptyDocument'] = minified(empty_document())
    return built


def joined(built, language):
    """The string IC-115 copies, joined as CR-562 section 5 states.

    Used here only to report its size; the shell does the same join.
    """
    return (built[language] + '\n\nschemaVersion: ' + built['schemaVersion']
            + '\n\n' + FENCE + 'json\n' + built['schema'] + '\n' + FENCE
            + '\n\n' + FENCE + 'json\n' + built['emptyDocument'] + '\n'
            + FENCE + '\n')


def sizes(built):
    """Bytes of each part and of each copied string, for the report line."""
    def count(text):
        return len(text.encode('utf-8'))
    return ('ja %d, en %d, schema %d, empty document %d; copied ja %d, en %d '
            'byte(s)' % (count(built['ja']), count(built['en']),
                         count(built['schema']), count(built['emptyDocument']),
                         count(joined(built, 'ja')), count(joined(built, 'en'))))


def main():
    """Write the artifact, or say whether the one on disk still matches.

    @purity non-pure
    """
    built = build()
    body = json.dumps(built, ensure_ascii=False, indent=1) + '\n'
    if '--check' in sys.argv:
        if not os.path.exists(OUT):
            say('PROBLEM  %s has not been written yet' % REL_OUT)
            return 1
        on_disk = io.open(OUT, encoding='utf-8', newline='').read()
        if on_disk != body:
            say('PROBLEM  %s has drifted from its manuscripts -- run '
                '`python %s`' % (REL_OUT, REL_SELF))
            return 1
        say('OK       the image-to-GRS-JSON prompt matches its manuscripts '
            '(%s)' % sizes(built))
        return 0
    io.open(OUT, 'w', encoding='utf-8', newline='\n').write(body)
    say('wrote %s (%s)' % (REL_OUT, sizes(built)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
