"""Fill the metrics block at the head of the defect ledger.

    python tools/ledger_metrics.py            # rewrite the block
    python tools/ledger_metrics.py --check    # fail if it is out of date

WHY THIS IS GENERATED. A count written by hand goes stale, and this round
watched it happen three times in other places -- a roster that stopped at an
old row id, a palette list that stopped at 34, a version-history sentence that
still said 78. The ledger's own totals are the last place that should be
trusted to a human's arithmetic.

WHAT IS *NOT* GENERATED. The 「セッション開始時」 row. Only the session that
starts knows what it started from, so it writes that line once, by hand, at
the head of its round -- and everything else here is derived from it and from
the table below. A session that forgets leaves yesterday's baseline standing,
which is visible rather than silent.

Run with PYTHONIOENCODING=utf-8.
"""
import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LEDGER = os.path.join(ROOT, 'docs', 'development-records', 'defects.md')
REL = 'docs/development-records/defects.md'

BEGIN = '<!-- ledger-metrics: begin -- generated by tools/ledger_metrics.py -->'
END = '<!-- ledger-metrics: end -->'

# The order the ladder is walked in, which is the order 「ステータスの定義」
# prints them. A status the table gains and this list does not is reported
# rather than dropped.
LADDER = ['未検討', '追加裁定待ち', '仕様確定', '実装待ち', '実装中',
          'テスト中', 'テスト待ち', 'テスト完了', '取下げ']


def counts(text):
    """How many rows stand at each status, and how many rows there are."""
    seen = {}
    rows = 0
    for line in text.split('\n'):
        if not line.startswith('| D-'):
            continue
        cells = line.split('|')
        if len(cells) != 11:
            raise SystemExit('%s: row %s has %d cells, not 11'
                             % (REL, cells[1].strip(), len(cells)))
        rows += 1
        status = cells[6].strip().strip('`')
        seen[status] = seen.get(status, 0) + 1
    return rows, seen


def parse_start(block):
    """The 「セッション開始時」 line the session wrote by hand."""
    for line in block.split('\n'):
        if line.startswith('| セッション開始時'):
            cells = [c.strip() for c in line.split('|')]
            when = cells[1].replace('セッション開始時', '').strip()
            return when, [c for c in cells[2:-1]]
    return None, None


def signed(n):
    return '±0' if n == 0 else ('+%d' % n if n > 0 else str(n))


def block_of(when, start_cells, rows, seen, today):
    order = [s for s in LADDER if s in seen or (start_cells and any(start_cells))]
    order = [s for s in LADDER if seen.get(s, 0) > 0] if start_cells is None else \
        [s for s in LADDER]
    head = '| | 総件数 | ' + ' | '.join(order) + ' |'
    rule = '| --- | --: | ' + ' | '.join(['--:'] * len(order)) + ' |'
    now = [rows] + [seen.get(s, 0) for s in order]
    if start_cells is None or len(start_cells) != len(now):
        start = ['—'] * len(now)
        diff = ['—'] * len(now)
    else:
        try:
            start_n = [int(c) for c in start_cells]
            diff = [signed(a - b) for a, b in zip(now, start_n)]
            start = [str(n) for n in start_n]
        except ValueError:
            start = list(start_cells)
            diff = ['—'] * len(now)
    lines = [
        BEGIN,
        '',
        '### ⭐ 件数（**`tools/ledger_metrics.py` が刷る。手で書き換えない**）',
        '',
        head,
        rule,
        '| セッション開始時 %s | ' % when + ' | '.join(start) + ' |',
        '| 最新 %s | ' % today + ' | '.join(str(n) for n in now) + ' |',
        '| ⭐ 差分 | ' + ' | '.join(diff) + ' |',
        '',
        '⚠️ **「セッション開始時」の行だけは、巡を始めた者が手で書く。**'
        '⛔ 始めた者にしか分からない。書き忘れると前日の値が残る —— **黙って消えるよりよい。**',
        '',
        END,
    ]
    return '\n'.join(lines)


def main():
    text = io.open(LEDGER, encoding='utf-8').read()
    rows, seen = counts(text)
    unknown = sorted(s for s in seen if s not in LADDER)
    if unknown:
        raise SystemExit('%s: status not on the ladder: %s' % (REL, unknown))

    i, j = text.find(BEGIN), text.find(END)
    if i < 0 or j < 0:
        raise SystemExit('%s: the metrics block is missing -- add %s / %s'
                         % (REL, BEGIN, END))
    old = text[i:j + len(END)]
    when, start_cells = parse_start(old)
    if when is None:
        raise SystemExit('%s: the block has no 「セッション開始時」 line' % REL)

    today = re.search(r'最新 ([0-9-]+)', old)
    today = today.group(1) if today else when
    if '--today' in sys.argv:
        today = sys.argv[sys.argv.index('--today') + 1]

    fresh = block_of(when, start_cells, rows, seen, today)
    if '--check' in sys.argv:
        if old != fresh:
            print('DRIFTED  %s: the metrics block no longer matches the table '
                  '-- rerun tools/ledger_metrics.py' % REL)
            return 1
        print('OK       %s: %d row(s), the metrics block matches' % (REL, rows))
        return 0
    io.open(LEDGER, 'w', encoding='utf-8', newline='\n').write(
        text[:i] + fresh + text[j + len(END):])
    print('wrote the metrics block (%d rows)' % rows)
    return 0


if __name__ == '__main__':
    sys.exit(main())
