"""Fill the metrics block at the head of the defect ledger.

    python tools/ledger_metrics.py --start    # AT THE HEAD OF A ROUND: snapshot now
    python tools/ledger_metrics.py            # rewrite the latest row and the delta
    python tools/ledger_metrics.py --check    # fail if the counts are out of date

WHY THIS IS GENERATED. A count written by hand goes stale, and this round
watched it happen three times in other places -- a roster that stopped at an
old row id, a palette list that stopped at 34, a version-history sentence that
still said 78. The ledger's own totals are the last place that should be
trusted to a human's arithmetic.

THE BASELINE IS MEASURED TOO, and `--start` is what takes it. An earlier draft
had the session write that row by hand; the user refused it, and rightly --
the number is measurable, and a measurable number written by hand is the very
fault this file exists to stop. A round runs `--start` once at its head and
nothing else touches that row.

⚠️ IT CARRIES A TIME AND NOT A DATE. More than one round runs in a day, and
two baselines stamped with the same date cannot be told apart.

⛔ `--check` COMPARES THE COUNTS AND NOT THE STAMP. The latest row's time moves
whenever the block is reprinted, and a check that failed on the clock would be
a check nobody could keep green.

Run with PYTHONIOENCODING=utf-8.
"""
import datetime
import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LEDGER = os.path.join(ROOT, 'docs', 'development-records', 'defects.md')
REL = 'docs/development-records/defects.md'

# The ledger is TWO FILES from 2026-09-02 (the harvest the user ruled for on
# 2026-09-01). A row that reaches 実測済 or 取下げ is moved out of `defects.md`
# into `fixed-defects.md` word for word, so the open ledger stays short enough
# to read through.
#
# EVERY COUNT HERE READS BOTH. A tool that read only the first would measure an
# emptier and emptier table and print the harvest as progress: the totals would
# fall by exactly the number of rows that were FINISHED, which is the one
# number that must not move when no work was done.
HARVEST = os.path.join(ROOT, 'docs', 'development-records', 'fixed-defects.md')
REL_HARVEST = 'docs/development-records/fixed-defects.md'

BEGIN = '<!-- ledger-metrics: begin -- generated by tools/ledger_metrics.py -->'
END = '<!-- ledger-metrics: end -->'

# The order the ladder is walked in, which is the order 「ステータスの定義」
# prints them. A status the table gains and this list does not is reported
# rather than dropped.
#
# ⭐ THE EIGHT STATES OF 2026-09-01 (利用者の裁定). Every non-terminal state is
# named for WHAT IT IS WAITING ON, so the name says who acts next. The ten they
# replaced mixed two axes -- how far the work had got, and who was holding it --
# and the second axis rotted: measured, テスト中 (20 rows) and テスト待ち
# (20 rows) meant the same thing in practice, and テスト待ち was not even in the
# definitions table until 2026-09-01. ⛔ テスト完了 also carried two claims at
# once -- "the automated tests are green" and "somebody opened the shipped build
# and measured it" -- which are not the same claim. 実測待ち and 実測済 are those
# two claims, held apart.
LADDER = ['未検討', '裁定待ち', '仕様待ち', '実装待ち',
          '試験待ち', '実測待ち', '実測済', '取下げ']

# ⛔ THE TWO THAT COUNT AS FINISHED. Everything else is 残件, and 残件 going down
# is what progress means from 2026-08-30 (利用者の裁定). ⚠️ 実測済 takes the seat
# テスト完了 held: a row is finished when it has been MEASURED in the shipped
# build, not when its automated tests went green.
DONE = ['実測済', '取下げ']

# ⚠️ THE TEN NAMES THE LEDGER USED UNTIL 2026-09-01, in the order they were
# printed in, and where each one lands now. This exists for ONE reason: a
# baseline row taken under the old names has twelve cells while the new header
# has ten, and without folding one onto the other the length guard in
# `block_of` would take every cell to — and the round would silently lose the
# progress it had already measured. That exact failure happened once before,
# on 2026-08-30, when 残件 was added in front of 総件数.
#
# ⛔ テスト完了 FOLDS ENTIRELY INTO 実測済, and that is a measured fact rather than
# a guess: check 28 (check-live-verification.py) has held the count of finished
# rows carrying no measurement at a baseline of 0 since 2026-08-30, and it fails
# the moment that count rises. A baseline taken after that date therefore cannot
# hold a テスト完了 row that still owed a look at the real thing.
OLD_LADDER = ['未検討', '追加裁定待ち', '仕様確定', '仕様書反映済み', '実装待ち',
              '実装中', 'テスト中', 'テスト待ち', 'テスト完了', '取下げ']
RENAMED = {
    '未検討': '未検討',
    '追加裁定待ち': '裁定待ち',
    '仕様確定': '仕様待ち',
    '仕様書反映済み': '実装待ち',
    '実装待ち': '実装待ち',
    '実装中': '実装待ち',
    'テスト中': '試験待ち',
    'テスト待ち': '試験待ち',
    'テスト完了': '実測済',
    '取下げ': '取下げ',
}


def migrate(start_cells):
    """An old twelve-cell baseline row, re-expressed under the eight names.

    ⭐ 残件 AND 総件数 KEEP THEIR VALUES: 残件 is everything that has not reached
    the two finished states, and the two finished states map onto the two
    finished states. Only the columns between them are folded.

    ⚠️ It returns the row untouched when the row is not the old shape, so this
    is a no-op from the first baseline taken under the new names onward.
    """
    if start_cells is None or len(start_cells) != 2 + len(OLD_LADDER):
        return start_cells
    try:
        numbers = [int(c) for c in start_cells]
    except ValueError:
        return start_cells                # a row of dashes; nothing to fold
    folded = dict((name, 0) for name in LADDER)
    for name, count in zip(OLD_LADDER, numbers[2:]):
        folded[RENAMED[name]] += count
    return [str(numbers[0]), str(numbers[1])] + [str(folded[n]) for n in LADDER]


def counts(*named_texts):
    """How many rows stand at each status, and how many rows there are.

    It takes BOTH files of the ledger as (relative path, text) pairs. A row id
    may stand in only one of them: reading a row twice would be worse than
    never reading it, because the totals would still look plausible.
    """
    seen = {}
    rows = 0
    where = {}
    for rel, text in named_texts:
        for line in text.splitlines():
            if not line.startswith('| D-'):
                continue
            cells = line.split('|')
            if len(cells) != 11:
                raise SystemExit('%s: row %s has %d cells, not 11'
                                 % (rel, cells[1].strip(), len(cells)))
            row_id = cells[1].strip()
            if row_id in where:
                raise SystemExit('%s: row %s is also in %s -- a row lives in '
                                 'exactly one of the two files'
                                 % (rel, row_id, where[row_id]))
            where[row_id] = rel
            rows += 1
            status = cells[6].strip().strip('`')
            seen[status] = seen.get(status, 0) + 1
    return rows, seen


def parse_start(block):
    """The baseline row, as `--start` last took it."""
    for line in block.split('\n'):
        if line.startswith('| セッション開始時'):
            cells = [c.strip() for c in line.split('|')]
            when = cells[1].replace('セッション開始時', '').strip()
            # ⭐ A baseline taken under the ten old names is folded onto the
            # eight, so a round that opened before 2026-09-01 keeps its delta.
            return when, migrate([c for c in cells[2:-1]])
    return None, None


def stamp():
    """Now, to the minute. ⚠️ A date alone cannot tell two rounds of one day apart."""
    return datetime.datetime.now().strftime('%Y-%m-%d %H:%M')


def signed(n):
    return '±0' if n == 0 else ('+%d' % n if n > 0 else str(n))


def block_of(when, start_cells, rows, seen, today):
    # ⛔ EVERY RUNG OF THE LADDER IS A COLUMN, empty or not. A column that
    # appeared only when a row stood on it would change the header's width from
    # one run to the next, and the baseline row printed under it would stop
    # lining up with the header it was measured against.
    order = [s for s in LADDER if seen.get(s, 0) > 0] if start_cells is None \
        else list(LADDER)
    head = '| | 残件 | 総件数 | ' + ' | '.join(order) + ' |'
    rule = '| --- | --: | --: | ' + ' | '.join(['--:'] * len(order)) + ' |'
    # ⭐ 残件 IS THE PROGRESS MEASURE (利用者の裁定 2026-08-30): everything that
    # has not reached 実測済 or 取下げ. ⚠️ It is derived, never counted by
    # hand -- the whole reason this file exists.
    now = [rows - sum(seen.get(s, 0) for s in DONE), rows]         + [seen.get(s, 0) for s in order]
    if start_cells is None or len(start_cells) != len(now):
        start = ['—'] * len(now)
        diff = ['—'] * len(now)
    else:
        try:
            start_n = [int(c) for c in start_cells]
            diff = [signed(a - b) for a, b in zip(now, start_n)]
            start = [str(n) for n in start_n]
        except ValueError:
            start = list(start_cells)
            diff = ['—'] * len(now)
    lines = [
        BEGIN,
        '',
        '### ⭐ 件数（**`tools/ledger_metrics.py` が刷る。手で書き換えない**）',
        '',
        head,
        rule,
        '| セッション開始時 %s | ' % when + ' | '.join(start) + ' |',
        '| 最新 %s | ' % today + ' | '.join(str(n) for n in now) + ' |',
        '| ⭐ 差分 | ' + ' | '.join(diff) + ' |',
        '',
        '⚠️ **巡の頭で `python tools/ledger_metrics.py --start` を 1 度走らせる。**'
        '⛔ **手で書かない** —— 測れる数を手で書けば必ず腐る。'
        '⚠️ **時刻まで持つ** —— 1 日に複数の巡が走るので、日付だけでは見分けられない。',
        '',
        '⛔⛔ **上の数は 2 ファイルの合計である** —— 本書と '
        '[`fixed-defects.md`](fixed-defects.md)。'
        '⚠️ **合計で数えるのは、刈り取りが進歩に見えないようにするためである** —— '
        '**片方だけを数えれば、仕事を終えた行の数ぶん総件数が減り、'
        '何もしていない巡が前進に見える。**',
        '',
        END,
    ]
    return '\n'.join(lines)


def main():
    text = io.open(LEDGER, encoding='utf-8').read()
    harvested = (io.open(HARVEST, encoding='utf-8').read()
                 if os.path.exists(HARVEST) else '')
    rows, seen = counts((REL, text), (REL_HARVEST, harvested))
    unknown = sorted(s for s in seen if s not in LADDER)
    if unknown:
        raise SystemExit('%s: status not on the ladder: %s' % (REL, unknown))

    i, j = text.find(BEGIN), text.find(END)
    if i < 0 or j < 0:
        raise SystemExit('%s: the metrics block is missing -- add %s / %s'
                         % (REL, BEGIN, END))
    old = text[i:j + len(END)]
    when, start_cells = parse_start(old)
    if when is None:
        raise SystemExit('%s: the block has no 「セッション開始時」 line' % REL)

    held = re.search(r'最新 ([0-9: -]+?) \|', old)
    held = held.group(1).strip() if held else when

    if '--start' in sys.argv:
        # ⭐ The baseline IS this measurement. Both rows carry it, so the delta
        # opens at zero and every later run is measured against a real reading.
        # ⛔ THE FIRST CELL IS 残件 AND WAS MISSING UNTIL 2026-08-30. The ruling of
        # that day put 残件 in front of 総件数; this line still built one cell fewer
        # than `block_of` counts, so the length guard there took every cell to
        # — and the round opened with NO baseline at all -- silently, because a
        # row of dashes is what a first-ever run looks like too.
        now = stamp()
        left = rows - sum(seen.get(s, 0) for s in DONE)
        fresh = block_of(now,
                         [str(left), str(rows)]
                         + [str(seen.get(k, 0)) for k in LADDER],
                         rows, seen, now)
        io.open(LEDGER, 'w', encoding='utf-8', newline='\n').write(
            text[:i] + fresh + text[j + len(END):])
        print('baseline taken at %s (%d rows)' % (now, rows))
        return 0

    # ⛔ `--check` KEEPS THE STAMP THAT IS THERE, so only the counts are held.
    today = held if '--check' in sys.argv else stamp()
    fresh = block_of(when, start_cells, rows, seen, today)
    if '--check' in sys.argv:
        if old != fresh:
            print('DRIFTED  %s: the metrics block no longer matches the table '
                  '-- rerun tools/ledger_metrics.py' % REL)
            return 1
        print('OK       %s: %d row(s), the metrics block matches' % (REL, rows))
        return 0
    io.open(LEDGER, 'w', encoding='utf-8', newline='\n').write(
        text[:i] + fresh + text[j + len(END):])
    print('wrote the metrics block (%d rows)' % rows)
    return 0


if __name__ == '__main__':
    sys.exit(main())
